#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión del motor en tiempo de ejecución:2.0.50727.3603
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[System.Data.Linq.Mapping.DatabaseAttribute(Name="formFlows")]
public partial class DataClassesDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  partial void InsertAttrReglas(AttrReglas instance);
  partial void UpdateAttrReglas(AttrReglas instance);
  partial void DeleteAttrReglas(AttrReglas instance);
  #endregion
	
	public DataClassesDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["formFlowsConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<AttrReglas> AttrReglas
	{
		get
		{
			return this.GetTable<AttrReglas>();
		}
	}
}

[Table(Name="dbo.AttrReglas")]
public partial class AttrReglas : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private decimal _IDRegla;
	
	private string _NomRegal;
	
	private System.Nullable<decimal> _IDAttRelacionado;
	
	private string _NomModoEjecucion;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDReglaChanging(decimal value);
    partial void OnIDReglaChanged();
    partial void OnNomRegalChanging(string value);
    partial void OnNomRegalChanged();
    partial void OnIDAttRelacionadoChanging(System.Nullable<decimal> value);
    partial void OnIDAttRelacionadoChanged();
    partial void OnNomModoEjecucionChanging(string value);
    partial void OnNomModoEjecucionChanged();
    #endregion
	
	public AttrReglas()
	{
		OnCreated();
	}
	
	[Column(Storage="_IDRegla", AutoSync=AutoSync.OnInsert, DbType="Decimal(18,0) NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public decimal IDRegla
	{
		get
		{
			return this._IDRegla;
		}
		set
		{
			if ((this._IDRegla != value))
			{
				this.OnIDReglaChanging(value);
				this.SendPropertyChanging();
				this._IDRegla = value;
				this.SendPropertyChanged("IDRegla");
				this.OnIDReglaChanged();
			}
		}
	}
	
	[Column(Storage="_NomRegal", DbType="VarChar(50)")]
	public string NomRegal
	{
		get
		{
			return this._NomRegal;
		}
		set
		{
			if ((this._NomRegal != value))
			{
				this.OnNomRegalChanging(value);
				this.SendPropertyChanging();
				this._NomRegal = value;
				this.SendPropertyChanged("NomRegal");
				this.OnNomRegalChanged();
			}
		}
	}
	
	[Column(Storage="_IDAttRelacionado", DbType="Decimal(18,0)")]
	public System.Nullable<decimal> IDAttRelacionado
	{
		get
		{
			return this._IDAttRelacionado;
		}
		set
		{
			if ((this._IDAttRelacionado != value))
			{
				this.OnIDAttRelacionadoChanging(value);
				this.SendPropertyChanging();
				this._IDAttRelacionado = value;
				this.SendPropertyChanged("IDAttRelacionado");
				this.OnIDAttRelacionadoChanged();
			}
		}
	}
	
	[Column(Storage="_NomModoEjecucion", DbType="VarChar(50)")]
	public string NomModoEjecucion
	{
		get
		{
			return this._NomModoEjecucion;
		}
		set
		{
			if ((this._NomModoEjecucion != value))
			{
				this.OnNomModoEjecucionChanging(value);
				this.SendPropertyChanging();
				this._NomModoEjecucion = value;
				this.SendPropertyChanged("NomModoEjecucion");
				this.OnNomModoEjecucionChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}
#pragma warning restore 1591
