#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión del motor en tiempo de ejecución:2.0.50727.3603
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;
using System.Runtime.Serialization;



[System.Data.Linq.Mapping.DatabaseAttribute(Name="formFlows")]
public partial class DataClassesDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  partial void InsertAreas(Areas instance);
  partial void UpdateAreas(Areas instance);
  partial void DeleteAreas(Areas instance);
  partial void InsertAtributoInformacionGeneral(AtributoInformacionGeneral instance);
  partial void UpdateAtributoInformacionGeneral(AtributoInformacionGeneral instance);
  partial void DeleteAtributoInformacionGeneral(AtributoInformacionGeneral instance);
  partial void InsertAttrReglas(AttrReglas instance);
  partial void UpdateAttrReglas(AttrReglas instance);
  partial void DeleteAttrReglas(AttrReglas instance);
  partial void InsertFamiliaAtributo(FamiliaAtributo instance);
  partial void UpdateFamiliaAtributo(FamiliaAtributo instance);
  partial void DeleteFamiliaAtributo(FamiliaAtributo instance);
  partial void InsertFamiliaInformacionGeneral(FamiliaInformacionGeneral instance);
  partial void UpdateFamiliaInformacionGeneral(FamiliaInformacionGeneral instance);
  partial void DeleteFamiliaInformacionGeneral(FamiliaInformacionGeneral instance);
  partial void InsertFamiliaRevision(FamiliaRevision instance);
  partial void UpdateFamiliaRevision(FamiliaRevision instance);
  partial void DeleteFamiliaRevision(FamiliaRevision instance);
  partial void Insertobservaciones(observaciones instance);
  partial void Updateobservaciones(observaciones instance);
  partial void Deleteobservaciones(observaciones instance);
  partial void InsertTreeEstructuraItems(TreeEstructuraItems instance);
  partial void UpdateTreeEstructuraItems(TreeEstructuraItems instance);
  partial void DeleteTreeEstructuraItems(TreeEstructuraItems instance);
  partial void InsertTreeNodos(TreeNodos instance);
  partial void UpdateTreeNodos(TreeNodos instance);
  partial void DeleteTreeNodos(TreeNodos instance);
  partial void InsertCondicionesReglasOperadorAritmetico(CondicionesReglasOperadorAritmetico instance);
  partial void UpdateCondicionesReglasOperadorAritmetico(CondicionesReglasOperadorAritmetico instance);
  partial void DeleteCondicionesReglasOperadorAritmetico(CondicionesReglasOperadorAritmetico instance);
  partial void InsertCondicionesReglasOperadorLogico(CondicionesReglasOperadorLogico instance);
  partial void UpdateCondicionesReglasOperadorLogico(CondicionesReglasOperadorLogico instance);
  partial void DeleteCondicionesReglasOperadorLogico(CondicionesReglasOperadorLogico instance);
  partial void InsertAttrReglasCondicion(AttrReglasCondicion instance);
  partial void UpdateAttrReglasCondicion(AttrReglasCondicion instance);
  partial void DeleteAttrReglasCondicion(AttrReglasCondicion instance);
  partial void InsertAttrReglasAccion(AttrReglasAccion instance);
  partial void UpdateAttrReglasAccion(AttrReglasAccion instance);
  partial void DeleteAttrReglasAccion(AttrReglasAccion instance);
  partial void InsertProductoInformacionGeneral(ProductoInformacionGeneral instance);
  partial void UpdateProductoInformacionGeneral(ProductoInformacionGeneral instance);
  partial void DeleteProductoInformacionGeneral(ProductoInformacionGeneral instance);
  partial void InsertProductoTarifa(ProductoTarifa instance);
  partial void UpdateProductoTarifa(ProductoTarifa instance);
  partial void DeleteProductoTarifa(ProductoTarifa instance);
  partial void InsertProductoRevision(ProductoRevision instance);
  partial void UpdateProductoRevision(ProductoRevision instance);
  partial void DeleteProductoRevision(ProductoRevision instance);
  partial void InsertProductoEstructuraAttr(ProductoEstructuraAttr instance);
  partial void UpdateProductoEstructuraAttr(ProductoEstructuraAttr instance);
  partial void DeleteProductoEstructuraAttr(ProductoEstructuraAttr instance);
  #endregion
	
	public DataClassesDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["formFlowsConnectionString1"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<Areas> Areas
	{
		get
		{
			return this.GetTable<Areas>();
		}
	}
	
	public System.Data.Linq.Table<AtributoInformacionGeneral> AtributoInformacionGeneral
	{
		get
		{
			return this.GetTable<AtributoInformacionGeneral>();
		}
	}
	
	public System.Data.Linq.Table<AttrReglas> AttrReglas
	{
		get
		{
			return this.GetTable<AttrReglas>();
		}
	}
	
	public System.Data.Linq.Table<FamiliaAtributo> FamiliaAtributo
	{
		get
		{
			return this.GetTable<FamiliaAtributo>();
		}
	}
	
	public System.Data.Linq.Table<FamiliaInformacionGeneral> FamiliaInformacionGeneral
	{
		get
		{
			return this.GetTable<FamiliaInformacionGeneral>();
		}
	}
	
	public System.Data.Linq.Table<FamiliaRevision> FamiliaRevision
	{
		get
		{
			return this.GetTable<FamiliaRevision>();
		}
	}
	
	public System.Data.Linq.Table<observaciones> observaciones
	{
		get
		{
			return this.GetTable<observaciones>();
		}
	}
	
	public System.Data.Linq.Table<TreeEstructuraItems> TreeEstructuraItems
	{
		get
		{
			return this.GetTable<TreeEstructuraItems>();
		}
	}
	
	public System.Data.Linq.Table<TreeNodos> TreeNodos
	{
		get
		{
			return this.GetTable<TreeNodos>();
		}
	}
	
	public System.Data.Linq.Table<CondicionesReglasOperadorAritmetico> CondicionesReglasOperadorAritmetico
	{
		get
		{
			return this.GetTable<CondicionesReglasOperadorAritmetico>();
		}
	}
	
	public System.Data.Linq.Table<CondicionesReglasOperadorLogico> CondicionesReglasOperadorLogico
	{
		get
		{
			return this.GetTable<CondicionesReglasOperadorLogico>();
		}
	}
	
	public System.Data.Linq.Table<AttrReglasCondicion> AttrReglasCondicion
	{
		get
		{
			return this.GetTable<AttrReglasCondicion>();
		}
	}
	
	public System.Data.Linq.Table<AttrReglasAccion> AttrReglasAccion
	{
		get
		{
			return this.GetTable<AttrReglasAccion>();
		}
	}
	
	public System.Data.Linq.Table<ProductoInformacionGeneral> ProductoInformacionGeneral
	{
		get
		{
			return this.GetTable<ProductoInformacionGeneral>();
		}
	}
	
	public System.Data.Linq.Table<ProductoTarifa> ProductoTarifa
	{
		get
		{
			return this.GetTable<ProductoTarifa>();
		}
	}
	
	public System.Data.Linq.Table<ProductoRevision> ProductoRevision
	{
		get
		{
			return this.GetTable<ProductoRevision>();
		}
	}
	
	public System.Data.Linq.Table<ProductoEstructuraAttr> ProductoEstructuraAttr
	{
		get
		{
			return this.GetTable<ProductoEstructuraAttr>();
		}
	}
}

[Table(Name="dbo.Areas")]
[DataContract()]
public partial class Areas : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _Id;
	
	private string _Nombre;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    #endregion
	
	public Areas()
	{
		this.Initialize();
	}
	
	[Column(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	[DataMember(Order=1)]
	public int Id
	{
		get
		{
			return this._Id;
		}
		set
		{
			if ((this._Id != value))
			{
				this.OnIdChanging(value);
				this.SendPropertyChanging();
				this._Id = value;
				this.SendPropertyChanged("Id");
				this.OnIdChanged();
			}
		}
	}
	
	[Column(Storage="_Nombre", DbType="VarChar(255)")]
	[DataMember(Order=2)]
	public string Nombre
	{
		get
		{
			return this._Nombre;
		}
		set
		{
			if ((this._Nombre != value))
			{
				this.OnNombreChanging(value);
				this.SendPropertyChanging();
				this._Nombre = value;
				this.SendPropertyChanged("Nombre");
				this.OnNombreChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void Initialize()
	{
		OnCreated();
	}
	
	[OnDeserializing()]
	[System.ComponentModel.EditorBrowsableAttribute(EditorBrowsableState.Never)]
	public void OnDeserializing(StreamingContext context)
	{
		this.Initialize();
	}
}

[Table(Name="dbo.AtributoInformacionGeneral")]
[DataContract()]
public partial class AtributoInformacionGeneral : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _Id;
	
	private System.Nullable<int> _Identificador;
	
	private string _Autor;
	
	private System.Nullable<int> _Version;
	
	private System.Nullable<System.DateTime> _FechaCreacion;
	
	private System.Nullable<System.DateTime> _FechaVigenciaDesde;
	
	private System.Nullable<System.DateTime> _FechaVigenciaHasta;
	
	private string _Nombre;
	
	private string _Descripcion;
	
	private System.Nullable<byte> _EsModificable;
	
	private EntitySet<FamiliaAtributo> _FamiliaAtributo;
	
	private bool serializing;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnIdentificadorChanging(System.Nullable<int> value);
    partial void OnIdentificadorChanged();
    partial void OnAutorChanging(string value);
    partial void OnAutorChanged();
    partial void OnVersionChanging(System.Nullable<int> value);
    partial void OnVersionChanged();
    partial void OnFechaCreacionChanging(System.Nullable<System.DateTime> value);
    partial void OnFechaCreacionChanged();
    partial void OnFechaVigenciaDesdeChanging(System.Nullable<System.DateTime> value);
    partial void OnFechaVigenciaDesdeChanged();
    partial void OnFechaVigenciaHastaChanging(System.Nullable<System.DateTime> value);
    partial void OnFechaVigenciaHastaChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnDescripcionChanging(string value);
    partial void OnDescripcionChanged();
    partial void OnEsModificableChanging(System.Nullable<byte> value);
    partial void OnEsModificableChanged();
    #endregion
	
	public AtributoInformacionGeneral()
	{
		this.Initialize();
	}
	
	[Column(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	[DataMember(Order=1)]
	public int Id
	{
		get
		{
			return this._Id;
		}
		set
		{
			if ((this._Id != value))
			{
				this.OnIdChanging(value);
				this.SendPropertyChanging();
				this._Id = value;
				this.SendPropertyChanged("Id");
				this.OnIdChanged();
			}
		}
	}
	
	[Column(Storage="_Identificador", DbType="Int")]
	[DataMember(Order=2)]
	public System.Nullable<int> Identificador
	{
		get
		{
			return this._Identificador;
		}
		set
		{
			if ((this._Identificador != value))
			{
				this.OnIdentificadorChanging(value);
				this.SendPropertyChanging();
				this._Identificador = value;
				this.SendPropertyChanged("Identificador");
				this.OnIdentificadorChanged();
			}
		}
	}
	
	[Column(Storage="_Autor", DbType="VarChar(255)")]
	[DataMember(Order=3)]
	public string Autor
	{
		get
		{
			return this._Autor;
		}
		set
		{
			if ((this._Autor != value))
			{
				this.OnAutorChanging(value);
				this.SendPropertyChanging();
				this._Autor = value;
				this.SendPropertyChanged("Autor");
				this.OnAutorChanged();
			}
		}
	}
	
	[Column(Storage="_Version", DbType="Int")]
	[DataMember(Order=4)]
	public System.Nullable<int> Version
	{
		get
		{
			return this._Version;
		}
		set
		{
			if ((this._Version != value))
			{
				this.OnVersionChanging(value);
				this.SendPropertyChanging();
				this._Version = value;
				this.SendPropertyChanged("Version");
				this.OnVersionChanged();
			}
		}
	}
	
	[Column(Storage="_FechaCreacion", DbType="DateTime")]
	[DataMember(Order=5)]
	public System.Nullable<System.DateTime> FechaCreacion
	{
		get
		{
			return this._FechaCreacion;
		}
		set
		{
			if ((this._FechaCreacion != value))
			{
				this.OnFechaCreacionChanging(value);
				this.SendPropertyChanging();
				this._FechaCreacion = value;
				this.SendPropertyChanged("FechaCreacion");
				this.OnFechaCreacionChanged();
			}
		}
	}
	
	[Column(Storage="_FechaVigenciaDesde", DbType="DateTime")]
	[DataMember(Order=6)]
	public System.Nullable<System.DateTime> FechaVigenciaDesde
	{
		get
		{
			return this._FechaVigenciaDesde;
		}
		set
		{
			if ((this._FechaVigenciaDesde != value))
			{
				this.OnFechaVigenciaDesdeChanging(value);
				this.SendPropertyChanging();
				this._FechaVigenciaDesde = value;
				this.SendPropertyChanged("FechaVigenciaDesde");
				this.OnFechaVigenciaDesdeChanged();
			}
		}
	}
	
	[Column(Storage="_FechaVigenciaHasta", DbType="DateTime")]
	[DataMember(Order=7)]
	public System.Nullable<System.DateTime> FechaVigenciaHasta
	{
		get
		{
			return this._FechaVigenciaHasta;
		}
		set
		{
			if ((this._FechaVigenciaHasta != value))
			{
				this.OnFechaVigenciaHastaChanging(value);
				this.SendPropertyChanging();
				this._FechaVigenciaHasta = value;
				this.SendPropertyChanged("FechaVigenciaHasta");
				this.OnFechaVigenciaHastaChanged();
			}
		}
	}
	
	[Column(Storage="_Nombre", DbType="VarChar(100)")]
	[DataMember(Order=8)]
	public string Nombre
	{
		get
		{
			return this._Nombre;
		}
		set
		{
			if ((this._Nombre != value))
			{
				this.OnNombreChanging(value);
				this.SendPropertyChanging();
				this._Nombre = value;
				this.SendPropertyChanged("Nombre");
				this.OnNombreChanged();
			}
		}
	}
	
	[Column(Storage="_Descripcion", DbType="VarChar(MAX)")]
	[DataMember(Order=9)]
	public string Descripcion
	{
		get
		{
			return this._Descripcion;
		}
		set
		{
			if ((this._Descripcion != value))
			{
				this.OnDescripcionChanging(value);
				this.SendPropertyChanging();
				this._Descripcion = value;
				this.SendPropertyChanged("Descripcion");
				this.OnDescripcionChanged();
			}
		}
	}
	
	[Column(Storage="_EsModificable", DbType="TinyInt")]
	[DataMember(Order=10)]
	public System.Nullable<byte> EsModificable
	{
		get
		{
			return this._EsModificable;
		}
		set
		{
			if ((this._EsModificable != value))
			{
				this.OnEsModificableChanging(value);
				this.SendPropertyChanging();
				this._EsModificable = value;
				this.SendPropertyChanged("EsModificable");
				this.OnEsModificableChanged();
			}
		}
	}
	
	[Association(Name="AtributoInformacionGeneral_FamiliaAtributo", Storage="_FamiliaAtributo", ThisKey="Id", OtherKey="idAtributo")]
	[DataMember(Order=11, EmitDefaultValue=false)]
	public EntitySet<FamiliaAtributo> FamiliaAtributo
	{
		get
		{
			if ((this.serializing 
						&& (this._FamiliaAtributo.HasLoadedOrAssignedValues == false)))
			{
				return null;
			}
			return this._FamiliaAtributo;
		}
		set
		{
			this._FamiliaAtributo.Assign(value);
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_FamiliaAtributo(FamiliaAtributo entity)
	{
		this.SendPropertyChanging();
		entity.AtributoInformacionGeneral = this;
	}
	
	private void detach_FamiliaAtributo(FamiliaAtributo entity)
	{
		this.SendPropertyChanging();
		entity.AtributoInformacionGeneral = null;
	}
	
	private void Initialize()
	{
		this._FamiliaAtributo = new EntitySet<FamiliaAtributo>(new Action<FamiliaAtributo>(this.attach_FamiliaAtributo), new Action<FamiliaAtributo>(this.detach_FamiliaAtributo));
		OnCreated();
	}
	
	[OnDeserializing()]
	[System.ComponentModel.EditorBrowsableAttribute(EditorBrowsableState.Never)]
	public void OnDeserializing(StreamingContext context)
	{
		this.Initialize();
	}
	
	[OnSerializing()]
	[System.ComponentModel.EditorBrowsableAttribute(EditorBrowsableState.Never)]
	public void OnSerializing(StreamingContext context)
	{
		this.serializing = true;
	}
	
	[OnSerialized()]
	[System.ComponentModel.EditorBrowsableAttribute(EditorBrowsableState.Never)]
	public void OnSerialized(StreamingContext context)
	{
		this.serializing = false;
	}
}

[Table(Name="dbo.AttrReglas")]
[DataContract()]
public partial class AttrReglas : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private decimal _IDRegla;
	
	private string _NomRegal;
	
	private System.Nullable<decimal> _IDAttRelacionado;
	
	private string _NomModoEjecucion;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDReglaChanging(decimal value);
    partial void OnIDReglaChanged();
    partial void OnNomRegalChanging(string value);
    partial void OnNomRegalChanged();
    partial void OnIDAttRelacionadoChanging(System.Nullable<decimal> value);
    partial void OnIDAttRelacionadoChanged();
    partial void OnNomModoEjecucionChanging(string value);
    partial void OnNomModoEjecucionChanged();
    #endregion
	
	public AttrReglas()
	{
		this.Initialize();
	}
	
	[Column(Storage="_IDRegla", AutoSync=AutoSync.OnInsert, DbType="Decimal(18,0) NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	[DataMember(Order=1)]
	public decimal IDRegla
	{
		get
		{
			return this._IDRegla;
		}
		set
		{
			if ((this._IDRegla != value))
			{
				this.OnIDReglaChanging(value);
				this.SendPropertyChanging();
				this._IDRegla = value;
				this.SendPropertyChanged("IDRegla");
				this.OnIDReglaChanged();
			}
		}
	}
	
	[Column(Storage="_NomRegal", DbType="VarChar(50)")]
	[DataMember(Order=2)]
	public string NomRegal
	{
		get
		{
			return this._NomRegal;
		}
		set
		{
			if ((this._NomRegal != value))
			{
				this.OnNomRegalChanging(value);
				this.SendPropertyChanging();
				this._NomRegal = value;
				this.SendPropertyChanged("NomRegal");
				this.OnNomRegalChanged();
			}
		}
	}
	
	[Column(Storage="_IDAttRelacionado", DbType="Decimal(18,0)")]
	[DataMember(Order=3)]
	public System.Nullable<decimal> IDAttRelacionado
	{
		get
		{
			return this._IDAttRelacionado;
		}
		set
		{
			if ((this._IDAttRelacionado != value))
			{
				this.OnIDAttRelacionadoChanging(value);
				this.SendPropertyChanging();
				this._IDAttRelacionado = value;
				this.SendPropertyChanged("IDAttRelacionado");
				this.OnIDAttRelacionadoChanged();
			}
		}
	}
	
	[Column(Storage="_NomModoEjecucion", DbType="VarChar(50)")]
	[DataMember(Order=4)]
	public string NomModoEjecucion
	{
		get
		{
			return this._NomModoEjecucion;
		}
		set
		{
			if ((this._NomModoEjecucion != value))
			{
				this.OnNomModoEjecucionChanging(value);
				this.SendPropertyChanging();
				this._NomModoEjecucion = value;
				this.SendPropertyChanged("NomModoEjecucion");
				this.OnNomModoEjecucionChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void Initialize()
	{
		OnCreated();
	}
	
	[OnDeserializing()]
	[System.ComponentModel.EditorBrowsableAttribute(EditorBrowsableState.Never)]
	public void OnDeserializing(StreamingContext context)
	{
		this.Initialize();
	}
}

[Table(Name="dbo.FamiliaAtributo")]
[DataContract()]
public partial class FamiliaAtributo : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _id;
	
	private System.Nullable<int> _idFamilia;
	
	private System.Nullable<int> _idAtributo;
	
	private EntityRef<AtributoInformacionGeneral> _AtributoInformacionGeneral;
	
	private EntityRef<FamiliaInformacionGeneral> _FamiliaInformacionGeneral;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnidFamiliaChanging(System.Nullable<int> value);
    partial void OnidFamiliaChanged();
    partial void OnidAtributoChanging(System.Nullable<int> value);
    partial void OnidAtributoChanged();
    #endregion
	
	public FamiliaAtributo()
	{
		this.Initialize();
	}
	
	[Column(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	[DataMember(Order=1)]
	public int id
	{
		get
		{
			return this._id;
		}
		set
		{
			if ((this._id != value))
			{
				this.OnidChanging(value);
				this.SendPropertyChanging();
				this._id = value;
				this.SendPropertyChanged("id");
				this.OnidChanged();
			}
		}
	}
	
	[Column(Storage="_idFamilia", DbType="Int")]
	[DataMember(Order=2)]
	public System.Nullable<int> idFamilia
	{
		get
		{
			return this._idFamilia;
		}
		set
		{
			if ((this._idFamilia != value))
			{
				if (this._FamiliaInformacionGeneral.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.OnidFamiliaChanging(value);
				this.SendPropertyChanging();
				this._idFamilia = value;
				this.SendPropertyChanged("idFamilia");
				this.OnidFamiliaChanged();
			}
		}
	}
	
	[Column(Storage="_idAtributo", DbType="Int")]
	[DataMember(Order=3)]
	public System.Nullable<int> idAtributo
	{
		get
		{
			return this._idAtributo;
		}
		set
		{
			if ((this._idAtributo != value))
			{
				if (this._AtributoInformacionGeneral.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.OnidAtributoChanging(value);
				this.SendPropertyChanging();
				this._idAtributo = value;
				this.SendPropertyChanged("idAtributo");
				this.OnidAtributoChanged();
			}
		}
	}
	
	[Association(Name="AtributoInformacionGeneral_FamiliaAtributo", Storage="_AtributoInformacionGeneral", ThisKey="idAtributo", OtherKey="Id", IsForeignKey=true)]
	public AtributoInformacionGeneral AtributoInformacionGeneral
	{
		get
		{
			return this._AtributoInformacionGeneral.Entity;
		}
		set
		{
			AtributoInformacionGeneral previousValue = this._AtributoInformacionGeneral.Entity;
			if (((previousValue != value) 
						|| (this._AtributoInformacionGeneral.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._AtributoInformacionGeneral.Entity = null;
					previousValue.FamiliaAtributo.Remove(this);
				}
				this._AtributoInformacionGeneral.Entity = value;
				if ((value != null))
				{
					value.FamiliaAtributo.Add(this);
					this._idAtributo = value.Id;
				}
				else
				{
					this._idAtributo = default(Nullable<int>);
				}
				this.SendPropertyChanged("AtributoInformacionGeneral");
			}
		}
	}
	
	[Association(Name="FamiliaInformacionGeneral_FamiliaAtributo", Storage="_FamiliaInformacionGeneral", ThisKey="idFamilia", OtherKey="Id", IsForeignKey=true)]
	public FamiliaInformacionGeneral FamiliaInformacionGeneral
	{
		get
		{
			return this._FamiliaInformacionGeneral.Entity;
		}
		set
		{
			FamiliaInformacionGeneral previousValue = this._FamiliaInformacionGeneral.Entity;
			if (((previousValue != value) 
						|| (this._FamiliaInformacionGeneral.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._FamiliaInformacionGeneral.Entity = null;
					previousValue.FamiliaAtributo.Remove(this);
				}
				this._FamiliaInformacionGeneral.Entity = value;
				if ((value != null))
				{
					value.FamiliaAtributo.Add(this);
					this._idFamilia = value.Id;
				}
				else
				{
					this._idFamilia = default(Nullable<int>);
				}
				this.SendPropertyChanged("FamiliaInformacionGeneral");
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void Initialize()
	{
		this._AtributoInformacionGeneral = default(EntityRef<AtributoInformacionGeneral>);
		this._FamiliaInformacionGeneral = default(EntityRef<FamiliaInformacionGeneral>);
		OnCreated();
	}
	
	[OnDeserializing()]
	[System.ComponentModel.EditorBrowsableAttribute(EditorBrowsableState.Never)]
	public void OnDeserializing(StreamingContext context)
	{
		this.Initialize();
	}
}

[Table(Name="dbo.FamiliaInformacionGeneral")]
[DataContract()]
public partial class FamiliaInformacionGeneral : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _Id;
	
	private System.Nullable<int> _Identificador;
	
	private string _Autor;
	
	private System.Nullable<int> _Version;
	
	private System.Nullable<System.DateTime> _FechaCreacion;
	
	private System.Nullable<System.DateTime> _FechaVigenciaDesde;
	
	private System.Nullable<System.DateTime> _FechaVigenciaHasta;
	
	private string _Nombre;
	
	private string _Grupo;
	
	private string _Estado;
	
	private string _Usuario;
	
	private EntitySet<FamiliaAtributo> _FamiliaAtributo;
	
	private bool serializing;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnIdentificadorChanging(System.Nullable<int> value);
    partial void OnIdentificadorChanged();
    partial void OnAutorChanging(string value);
    partial void OnAutorChanged();
    partial void OnVersionChanging(System.Nullable<int> value);
    partial void OnVersionChanged();
    partial void OnFechaCreacionChanging(System.Nullable<System.DateTime> value);
    partial void OnFechaCreacionChanged();
    partial void OnFechaVigenciaDesdeChanging(System.Nullable<System.DateTime> value);
    partial void OnFechaVigenciaDesdeChanged();
    partial void OnFechaVigenciaHastaChanging(System.Nullable<System.DateTime> value);
    partial void OnFechaVigenciaHastaChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnGrupoChanging(string value);
    partial void OnGrupoChanged();
    partial void OnEstadoChanging(string value);
    partial void OnEstadoChanged();
    partial void OnUsuarioChanging(string value);
    partial void OnUsuarioChanged();
    #endregion
	
	public FamiliaInformacionGeneral()
	{
		this.Initialize();
	}
	
	[Column(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	[DataMember(Order=1)]
	public int Id
	{
		get
		{
			return this._Id;
		}
		set
		{
			if ((this._Id != value))
			{
				this.OnIdChanging(value);
				this.SendPropertyChanging();
				this._Id = value;
				this.SendPropertyChanged("Id");
				this.OnIdChanged();
			}
		}
	}
	
	[Column(Storage="_Identificador", DbType="Int")]
	[DataMember(Order=2)]
	public System.Nullable<int> Identificador
	{
		get
		{
			return this._Identificador;
		}
		set
		{
			if ((this._Identificador != value))
			{
				this.OnIdentificadorChanging(value);
				this.SendPropertyChanging();
				this._Identificador = value;
				this.SendPropertyChanged("Identificador");
				this.OnIdentificadorChanged();
			}
		}
	}
	
	[Column(Storage="_Autor", DbType="VarChar(255)")]
	[DataMember(Order=3)]
	public string Autor
	{
		get
		{
			return this._Autor;
		}
		set
		{
			if ((this._Autor != value))
			{
				this.OnAutorChanging(value);
				this.SendPropertyChanging();
				this._Autor = value;
				this.SendPropertyChanged("Autor");
				this.OnAutorChanged();
			}
		}
	}
	
	[Column(Storage="_Version", DbType="Int")]
	[DataMember(Order=4)]
	public System.Nullable<int> Version
	{
		get
		{
			return this._Version;
		}
		set
		{
			if ((this._Version != value))
			{
				this.OnVersionChanging(value);
				this.SendPropertyChanging();
				this._Version = value;
				this.SendPropertyChanged("Version");
				this.OnVersionChanged();
			}
		}
	}
	
	[Column(Storage="_FechaCreacion", DbType="DateTime")]
	[DataMember(Order=5)]
	public System.Nullable<System.DateTime> FechaCreacion
	{
		get
		{
			return this._FechaCreacion;
		}
		set
		{
			if ((this._FechaCreacion != value))
			{
				this.OnFechaCreacionChanging(value);
				this.SendPropertyChanging();
				this._FechaCreacion = value;
				this.SendPropertyChanged("FechaCreacion");
				this.OnFechaCreacionChanged();
			}
		}
	}
	
	[Column(Storage="_FechaVigenciaDesde", DbType="DateTime")]
	[DataMember(Order=6)]
	public System.Nullable<System.DateTime> FechaVigenciaDesde
	{
		get
		{
			return this._FechaVigenciaDesde;
		}
		set
		{
			if ((this._FechaVigenciaDesde != value))
			{
				this.OnFechaVigenciaDesdeChanging(value);
				this.SendPropertyChanging();
				this._FechaVigenciaDesde = value;
				this.SendPropertyChanged("FechaVigenciaDesde");
				this.OnFechaVigenciaDesdeChanged();
			}
		}
	}
	
	[Column(Storage="_FechaVigenciaHasta", DbType="DateTime")]
	[DataMember(Order=7)]
	public System.Nullable<System.DateTime> FechaVigenciaHasta
	{
		get
		{
			return this._FechaVigenciaHasta;
		}
		set
		{
			if ((this._FechaVigenciaHasta != value))
			{
				this.OnFechaVigenciaHastaChanging(value);
				this.SendPropertyChanging();
				this._FechaVigenciaHasta = value;
				this.SendPropertyChanged("FechaVigenciaHasta");
				this.OnFechaVigenciaHastaChanged();
			}
		}
	}
	
	[Column(Storage="_Nombre", DbType="VarChar(100)")]
	[DataMember(Order=8)]
	public string Nombre
	{
		get
		{
			return this._Nombre;
		}
		set
		{
			if ((this._Nombre != value))
			{
				this.OnNombreChanging(value);
				this.SendPropertyChanging();
				this._Nombre = value;
				this.SendPropertyChanged("Nombre");
				this.OnNombreChanged();
			}
		}
	}
	
	[Column(Storage="_Grupo", DbType="VarChar(100)")]
	[DataMember(Order=9)]
	public string Grupo
	{
		get
		{
			return this._Grupo;
		}
		set
		{
			if ((this._Grupo != value))
			{
				this.OnGrupoChanging(value);
				this.SendPropertyChanging();
				this._Grupo = value;
				this.SendPropertyChanged("Grupo");
				this.OnGrupoChanged();
			}
		}
	}
	
	[Column(Storage="_Estado", DbType="VarChar(255)")]
	[DataMember(Order=10)]
	public string Estado
	{
		get
		{
			return this._Estado;
		}
		set
		{
			if ((this._Estado != value))
			{
				this.OnEstadoChanging(value);
				this.SendPropertyChanging();
				this._Estado = value;
				this.SendPropertyChanged("Estado");
				this.OnEstadoChanged();
			}
		}
	}
	
	[Column(Storage="_Usuario", DbType="VarChar(255)")]
	[DataMember(Order=11)]
	public string Usuario
	{
		get
		{
			return this._Usuario;
		}
		set
		{
			if ((this._Usuario != value))
			{
				this.OnUsuarioChanging(value);
				this.SendPropertyChanging();
				this._Usuario = value;
				this.SendPropertyChanged("Usuario");
				this.OnUsuarioChanged();
			}
		}
	}
	
	[Association(Name="FamiliaInformacionGeneral_FamiliaAtributo", Storage="_FamiliaAtributo", ThisKey="Id", OtherKey="idFamilia")]
	[DataMember(Order=12, EmitDefaultValue=false)]
	public EntitySet<FamiliaAtributo> FamiliaAtributo
	{
		get
		{
			if ((this.serializing 
						&& (this._FamiliaAtributo.HasLoadedOrAssignedValues == false)))
			{
				return null;
			}
			return this._FamiliaAtributo;
		}
		set
		{
			this._FamiliaAtributo.Assign(value);
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_FamiliaAtributo(FamiliaAtributo entity)
	{
		this.SendPropertyChanging();
		entity.FamiliaInformacionGeneral = this;
	}
	
	private void detach_FamiliaAtributo(FamiliaAtributo entity)
	{
		this.SendPropertyChanging();
		entity.FamiliaInformacionGeneral = null;
	}
	
	private void Initialize()
	{
		this._FamiliaAtributo = new EntitySet<FamiliaAtributo>(new Action<FamiliaAtributo>(this.attach_FamiliaAtributo), new Action<FamiliaAtributo>(this.detach_FamiliaAtributo));
		OnCreated();
	}
	
	[OnDeserializing()]
	[System.ComponentModel.EditorBrowsableAttribute(EditorBrowsableState.Never)]
	public void OnDeserializing(StreamingContext context)
	{
		this.Initialize();
	}
	
	[OnSerializing()]
	[System.ComponentModel.EditorBrowsableAttribute(EditorBrowsableState.Never)]
	public void OnSerializing(StreamingContext context)
	{
		this.serializing = true;
	}
	
	[OnSerialized()]
	[System.ComponentModel.EditorBrowsableAttribute(EditorBrowsableState.Never)]
	public void OnSerialized(StreamingContext context)
	{
		this.serializing = false;
	}
}

[Table(Name="dbo.FamiliaRevision")]
[DataContract()]
public partial class FamiliaRevision : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _id;
	
	private string _Estado;
	
	private string _Observacion;
	
	private string _Autor;
	
	private System.Nullable<System.DateTime> _Creado;
	
	private string _usuario;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnEstadoChanging(string value);
    partial void OnEstadoChanged();
    partial void OnObservacionChanging(string value);
    partial void OnObservacionChanged();
    partial void OnAutorChanging(string value);
    partial void OnAutorChanged();
    partial void OnCreadoChanging(System.Nullable<System.DateTime> value);
    partial void OnCreadoChanged();
    partial void OnusuarioChanging(string value);
    partial void OnusuarioChanged();
    #endregion
	
	public FamiliaRevision()
	{
		this.Initialize();
	}
	
	[Column(Storage="_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
	[DataMember(Order=1)]
	public int id
	{
		get
		{
			return this._id;
		}
		set
		{
			if ((this._id != value))
			{
				this.OnidChanging(value);
				this.SendPropertyChanging();
				this._id = value;
				this.SendPropertyChanged("id");
				this.OnidChanged();
			}
		}
	}
	
	[Column(Storage="_Estado", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
	[DataMember(Order=2)]
	public string Estado
	{
		get
		{
			return this._Estado;
		}
		set
		{
			if ((this._Estado != value))
			{
				this.OnEstadoChanging(value);
				this.SendPropertyChanging();
				this._Estado = value;
				this.SendPropertyChanged("Estado");
				this.OnEstadoChanged();
			}
		}
	}
	
	[Column(Storage="_Observacion", DbType="VarChar(1000) NOT NULL", CanBeNull=false)]
	[DataMember(Order=3)]
	public string Observacion
	{
		get
		{
			return this._Observacion;
		}
		set
		{
			if ((this._Observacion != value))
			{
				this.OnObservacionChanging(value);
				this.SendPropertyChanging();
				this._Observacion = value;
				this.SendPropertyChanged("Observacion");
				this.OnObservacionChanged();
			}
		}
	}
	
	[Column(Storage="_Autor", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
	[DataMember(Order=4)]
	public string Autor
	{
		get
		{
			return this._Autor;
		}
		set
		{
			if ((this._Autor != value))
			{
				this.OnAutorChanging(value);
				this.SendPropertyChanging();
				this._Autor = value;
				this.SendPropertyChanged("Autor");
				this.OnAutorChanged();
			}
		}
	}
	
	[Column(Storage="_Creado", DbType="DateTime")]
	[DataMember(Order=5)]
	public System.Nullable<System.DateTime> Creado
	{
		get
		{
			return this._Creado;
		}
		set
		{
			if ((this._Creado != value))
			{
				this.OnCreadoChanging(value);
				this.SendPropertyChanging();
				this._Creado = value;
				this.SendPropertyChanged("Creado");
				this.OnCreadoChanged();
			}
		}
	}
	
	[Column(Storage="_usuario", DbType="VarChar(255)")]
	[DataMember(Order=6)]
	public string usuario
	{
		get
		{
			return this._usuario;
		}
		set
		{
			if ((this._usuario != value))
			{
				this.OnusuarioChanging(value);
				this.SendPropertyChanging();
				this._usuario = value;
				this.SendPropertyChanged("usuario");
				this.OnusuarioChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void Initialize()
	{
		OnCreated();
	}
	
	[OnDeserializing()]
	[System.ComponentModel.EditorBrowsableAttribute(EditorBrowsableState.Never)]
	public void OnDeserializing(StreamingContext context)
	{
		this.Initialize();
	}
}

[Table(Name="dbo.observaciones")]
[DataContract()]
public partial class observaciones : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _id;
	
	private string _tarea;
	
	private string _observacion;
	
	private string _autor;
	
	private System.DateTime _fecha;
	
	private int _object_id;
	
	private string _object_class;
	
	private int _object_version;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OntareaChanging(string value);
    partial void OntareaChanged();
    partial void OnobservacionChanging(string value);
    partial void OnobservacionChanged();
    partial void OnautorChanging(string value);
    partial void OnautorChanged();
    partial void OnfechaChanging(System.DateTime value);
    partial void OnfechaChanged();
    partial void Onobject_idChanging(int value);
    partial void Onobject_idChanged();
    partial void Onobject_classChanging(string value);
    partial void Onobject_classChanged();
    partial void Onobject_versionChanging(int value);
    partial void Onobject_versionChanged();
    #endregion
	
	public observaciones()
	{
		this.Initialize();
	}
	
	[Column(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	[DataMember(Order=1)]
	public int id
	{
		get
		{
			return this._id;
		}
		set
		{
			if ((this._id != value))
			{
				this.OnidChanging(value);
				this.SendPropertyChanging();
				this._id = value;
				this.SendPropertyChanged("id");
				this.OnidChanged();
			}
		}
	}
	
	[Column(Storage="_tarea", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
	[DataMember(Order=2)]
	public string tarea
	{
		get
		{
			return this._tarea;
		}
		set
		{
			if ((this._tarea != value))
			{
				this.OntareaChanging(value);
				this.SendPropertyChanging();
				this._tarea = value;
				this.SendPropertyChanged("tarea");
				this.OntareaChanged();
			}
		}
	}
	
	[Column(Storage="_observacion", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
	[DataMember(Order=3)]
	public string observacion
	{
		get
		{
			return this._observacion;
		}
		set
		{
			if ((this._observacion != value))
			{
				this.OnobservacionChanging(value);
				this.SendPropertyChanging();
				this._observacion = value;
				this.SendPropertyChanged("observacion");
				this.OnobservacionChanged();
			}
		}
	}
	
	[Column(Storage="_autor", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
	[DataMember(Order=4)]
	public string autor
	{
		get
		{
			return this._autor;
		}
		set
		{
			if ((this._autor != value))
			{
				this.OnautorChanging(value);
				this.SendPropertyChanging();
				this._autor = value;
				this.SendPropertyChanged("autor");
				this.OnautorChanged();
			}
		}
	}
	
	[Column(Storage="_fecha", DbType="DateTime NOT NULL")]
	[DataMember(Order=5)]
	public System.DateTime fecha
	{
		get
		{
			return this._fecha;
		}
		set
		{
			if ((this._fecha != value))
			{
				this.OnfechaChanging(value);
				this.SendPropertyChanging();
				this._fecha = value;
				this.SendPropertyChanged("fecha");
				this.OnfechaChanged();
			}
		}
	}
	
	[Column(Storage="_object_id", DbType="Int NOT NULL")]
	[DataMember(Order=6)]
	public int object_id
	{
		get
		{
			return this._object_id;
		}
		set
		{
			if ((this._object_id != value))
			{
				this.Onobject_idChanging(value);
				this.SendPropertyChanging();
				this._object_id = value;
				this.SendPropertyChanged("object_id");
				this.Onobject_idChanged();
			}
		}
	}
	
	[Column(Storage="_object_class", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
	[DataMember(Order=7)]
	public string object_class
	{
		get
		{
			return this._object_class;
		}
		set
		{
			if ((this._object_class != value))
			{
				this.Onobject_classChanging(value);
				this.SendPropertyChanging();
				this._object_class = value;
				this.SendPropertyChanged("object_class");
				this.Onobject_classChanged();
			}
		}
	}
	
	[Column(Storage="_object_version", DbType="Int NOT NULL")]
	[DataMember(Order=8)]
	public int object_version
	{
		get
		{
			return this._object_version;
		}
		set
		{
			if ((this._object_version != value))
			{
				this.Onobject_versionChanging(value);
				this.SendPropertyChanging();
				this._object_version = value;
				this.SendPropertyChanged("object_version");
				this.Onobject_versionChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void Initialize()
	{
		OnCreated();
	}
	
	[OnDeserializing()]
	[System.ComponentModel.EditorBrowsableAttribute(EditorBrowsableState.Never)]
	public void OnDeserializing(StreamingContext context)
	{
		this.Initialize();
	}
}

[Table(Name="dbo.TreeEstructuraItems")]
[DataContract()]
public partial class TreeEstructuraItems : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private decimal _IDTreeEstructuraItem;
	
	private System.Nullable<bool> _EsRequerido;
	
	private System.Nullable<bool> _SoloLectura;
	
	private System.Nullable<bool> _MultiSeleccion;
	
	private string _SubTipo;
	
	private string _OrigenDeDatos;
	
	private string _Valores;
	
	private string _Ruta;
	
	private string _Metodo;
	
	private string _Tipo;
	
	private System.Nullable<decimal> _Largo;
	
	private System.Nullable<decimal> _Decimales;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDTreeEstructuraItemChanging(decimal value);
    partial void OnIDTreeEstructuraItemChanged();
    partial void OnEsRequeridoChanging(System.Nullable<bool> value);
    partial void OnEsRequeridoChanged();
    partial void OnSoloLecturaChanging(System.Nullable<bool> value);
    partial void OnSoloLecturaChanged();
    partial void OnMultiSeleccionChanging(System.Nullable<bool> value);
    partial void OnMultiSeleccionChanged();
    partial void OnSubTipoChanging(string value);
    partial void OnSubTipoChanged();
    partial void OnOrigenDeDatosChanging(string value);
    partial void OnOrigenDeDatosChanged();
    partial void OnValoresChanging(string value);
    partial void OnValoresChanged();
    partial void OnRutaChanging(string value);
    partial void OnRutaChanged();
    partial void OnMetodoChanging(string value);
    partial void OnMetodoChanged();
    partial void OnTipoChanging(string value);
    partial void OnTipoChanged();
    partial void OnLargoChanging(System.Nullable<decimal> value);
    partial void OnLargoChanged();
    partial void OnDecimalesChanging(System.Nullable<decimal> value);
    partial void OnDecimalesChanged();
    #endregion
	
	public TreeEstructuraItems()
	{
		this.Initialize();
	}
	
	[Column(Storage="_IDTreeEstructuraItem", DbType="Decimal(18,0) NOT NULL", IsPrimaryKey=true)]
	[DataMember(Order=1)]
	public decimal IDTreeEstructuraItem
	{
		get
		{
			return this._IDTreeEstructuraItem;
		}
		set
		{
			if ((this._IDTreeEstructuraItem != value))
			{
				this.OnIDTreeEstructuraItemChanging(value);
				this.SendPropertyChanging();
				this._IDTreeEstructuraItem = value;
				this.SendPropertyChanged("IDTreeEstructuraItem");
				this.OnIDTreeEstructuraItemChanged();
			}
		}
	}
	
	[Column(Storage="_EsRequerido", DbType="Bit")]
	[DataMember(Order=2)]
	public System.Nullable<bool> EsRequerido
	{
		get
		{
			return this._EsRequerido;
		}
		set
		{
			if ((this._EsRequerido != value))
			{
				this.OnEsRequeridoChanging(value);
				this.SendPropertyChanging();
				this._EsRequerido = value;
				this.SendPropertyChanged("EsRequerido");
				this.OnEsRequeridoChanged();
			}
		}
	}
	
	[Column(Storage="_SoloLectura", DbType="Bit")]
	[DataMember(Order=3)]
	public System.Nullable<bool> SoloLectura
	{
		get
		{
			return this._SoloLectura;
		}
		set
		{
			if ((this._SoloLectura != value))
			{
				this.OnSoloLecturaChanging(value);
				this.SendPropertyChanging();
				this._SoloLectura = value;
				this.SendPropertyChanged("SoloLectura");
				this.OnSoloLecturaChanged();
			}
		}
	}
	
	[Column(Storage="_MultiSeleccion", DbType="Bit")]
	[DataMember(Order=4)]
	public System.Nullable<bool> MultiSeleccion
	{
		get
		{
			return this._MultiSeleccion;
		}
		set
		{
			if ((this._MultiSeleccion != value))
			{
				this.OnMultiSeleccionChanging(value);
				this.SendPropertyChanging();
				this._MultiSeleccion = value;
				this.SendPropertyChanged("MultiSeleccion");
				this.OnMultiSeleccionChanged();
			}
		}
	}
	
	[Column(Storage="_SubTipo", DbType="VarChar(50)")]
	[DataMember(Order=5)]
	public string SubTipo
	{
		get
		{
			return this._SubTipo;
		}
		set
		{
			if ((this._SubTipo != value))
			{
				this.OnSubTipoChanging(value);
				this.SendPropertyChanging();
				this._SubTipo = value;
				this.SendPropertyChanged("SubTipo");
				this.OnSubTipoChanged();
			}
		}
	}
	
	[Column(Storage="_OrigenDeDatos", DbType="VarChar(50)")]
	[DataMember(Order=6)]
	public string OrigenDeDatos
	{
		get
		{
			return this._OrigenDeDatos;
		}
		set
		{
			if ((this._OrigenDeDatos != value))
			{
				this.OnOrigenDeDatosChanging(value);
				this.SendPropertyChanging();
				this._OrigenDeDatos = value;
				this.SendPropertyChanged("OrigenDeDatos");
				this.OnOrigenDeDatosChanged();
			}
		}
	}
	
	[Column(Storage="_Valores", DbType="VarChar(50)")]
	[DataMember(Order=7)]
	public string Valores
	{
		get
		{
			return this._Valores;
		}
		set
		{
			if ((this._Valores != value))
			{
				this.OnValoresChanging(value);
				this.SendPropertyChanging();
				this._Valores = value;
				this.SendPropertyChanged("Valores");
				this.OnValoresChanged();
			}
		}
	}
	
	[Column(Storage="_Ruta", DbType="VarChar(50)")]
	[DataMember(Order=8)]
	public string Ruta
	{
		get
		{
			return this._Ruta;
		}
		set
		{
			if ((this._Ruta != value))
			{
				this.OnRutaChanging(value);
				this.SendPropertyChanging();
				this._Ruta = value;
				this.SendPropertyChanged("Ruta");
				this.OnRutaChanged();
			}
		}
	}
	
	[Column(Storage="_Metodo", DbType="VarChar(50)")]
	[DataMember(Order=9)]
	public string Metodo
	{
		get
		{
			return this._Metodo;
		}
		set
		{
			if ((this._Metodo != value))
			{
				this.OnMetodoChanging(value);
				this.SendPropertyChanging();
				this._Metodo = value;
				this.SendPropertyChanged("Metodo");
				this.OnMetodoChanged();
			}
		}
	}
	
	[Column(Storage="_Tipo", DbType="VarChar(50)")]
	[DataMember(Order=10)]
	public string Tipo
	{
		get
		{
			return this._Tipo;
		}
		set
		{
			if ((this._Tipo != value))
			{
				this.OnTipoChanging(value);
				this.SendPropertyChanging();
				this._Tipo = value;
				this.SendPropertyChanged("Tipo");
				this.OnTipoChanged();
			}
		}
	}
	
	[Column(Storage="_Largo", DbType="Decimal(18,0)")]
	[DataMember(Order=11)]
	public System.Nullable<decimal> Largo
	{
		get
		{
			return this._Largo;
		}
		set
		{
			if ((this._Largo != value))
			{
				this.OnLargoChanging(value);
				this.SendPropertyChanging();
				this._Largo = value;
				this.SendPropertyChanged("Largo");
				this.OnLargoChanged();
			}
		}
	}
	
	[Column(Storage="_Decimales", DbType="Decimal(18,0)")]
	[DataMember(Order=12)]
	public System.Nullable<decimal> Decimales
	{
		get
		{
			return this._Decimales;
		}
		set
		{
			if ((this._Decimales != value))
			{
				this.OnDecimalesChanging(value);
				this.SendPropertyChanging();
				this._Decimales = value;
				this.SendPropertyChanged("Decimales");
				this.OnDecimalesChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void Initialize()
	{
		OnCreated();
	}
	
	[OnDeserializing()]
	[System.ComponentModel.EditorBrowsableAttribute(EditorBrowsableState.Never)]
	public void OnDeserializing(StreamingContext context)
	{
		this.Initialize();
	}
}

[Table(Name="dbo.TreeNodos")]
[DataContract()]
public partial class TreeNodos : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private decimal _IDTree;
	
	private string _NomTree;
	
	private System.Nullable<decimal> _IDParent;
	
	private System.Nullable<decimal> _IDAttr;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDTreeChanging(decimal value);
    partial void OnIDTreeChanged();
    partial void OnNomTreeChanging(string value);
    partial void OnNomTreeChanged();
    partial void OnIDParentChanging(System.Nullable<decimal> value);
    partial void OnIDParentChanged();
    partial void OnIDAttrChanging(System.Nullable<decimal> value);
    partial void OnIDAttrChanged();
    #endregion
	
	public TreeNodos()
	{
		this.Initialize();
	}
	
	[Column(Storage="_IDTree", AutoSync=AutoSync.OnInsert, DbType="Decimal(18,0) NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	[DataMember(Order=1)]
	public decimal IDTree
	{
		get
		{
			return this._IDTree;
		}
		set
		{
			if ((this._IDTree != value))
			{
				this.OnIDTreeChanging(value);
				this.SendPropertyChanging();
				this._IDTree = value;
				this.SendPropertyChanged("IDTree");
				this.OnIDTreeChanged();
			}
		}
	}
	
	[Column(Storage="_NomTree", DbType="VarChar(50)")]
	[DataMember(Order=2)]
	public string NomTree
	{
		get
		{
			return this._NomTree;
		}
		set
		{
			if ((this._NomTree != value))
			{
				this.OnNomTreeChanging(value);
				this.SendPropertyChanging();
				this._NomTree = value;
				this.SendPropertyChanged("NomTree");
				this.OnNomTreeChanged();
			}
		}
	}
	
	[Column(Storage="_IDParent", DbType="Decimal(18,0)")]
	[DataMember(Order=3)]
	public System.Nullable<decimal> IDParent
	{
		get
		{
			return this._IDParent;
		}
		set
		{
			if ((this._IDParent != value))
			{
				this.OnIDParentChanging(value);
				this.SendPropertyChanging();
				this._IDParent = value;
				this.SendPropertyChanged("IDParent");
				this.OnIDParentChanged();
			}
		}
	}
	
	[Column(Storage="_IDAttr", DbType="Decimal(18,0)")]
	[DataMember(Order=4)]
	public System.Nullable<decimal> IDAttr
	{
		get
		{
			return this._IDAttr;
		}
		set
		{
			if ((this._IDAttr != value))
			{
				this.OnIDAttrChanging(value);
				this.SendPropertyChanging();
				this._IDAttr = value;
				this.SendPropertyChanged("IDAttr");
				this.OnIDAttrChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void Initialize()
	{
		OnCreated();
	}
	
	[OnDeserializing()]
	[System.ComponentModel.EditorBrowsableAttribute(EditorBrowsableState.Never)]
	public void OnDeserializing(StreamingContext context)
	{
		this.Initialize();
	}
}

[Table(Name="dbo.CondicionesReglasOperadorAritmetico")]
[DataContract()]
public partial class CondicionesReglasOperadorAritmetico : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private decimal _id;
	
	private string _NombreOPAr;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(decimal value);
    partial void OnidChanged();
    partial void OnNombreOPArChanging(string value);
    partial void OnNombreOPArChanged();
    #endregion
	
	public CondicionesReglasOperadorAritmetico()
	{
		this.Initialize();
	}
	
	[Column(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Decimal(18,0) NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	[DataMember(Order=1)]
	public decimal id
	{
		get
		{
			return this._id;
		}
		set
		{
			if ((this._id != value))
			{
				this.OnidChanging(value);
				this.SendPropertyChanging();
				this._id = value;
				this.SendPropertyChanged("id");
				this.OnidChanged();
			}
		}
	}
	
	[Column(Storage="_NombreOPAr", DbType="VarChar(50)")]
	[DataMember(Order=2)]
	public string NombreOPAr
	{
		get
		{
			return this._NombreOPAr;
		}
		set
		{
			if ((this._NombreOPAr != value))
			{
				this.OnNombreOPArChanging(value);
				this.SendPropertyChanging();
				this._NombreOPAr = value;
				this.SendPropertyChanged("NombreOPAr");
				this.OnNombreOPArChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void Initialize()
	{
		OnCreated();
	}
	
	[OnDeserializing()]
	[System.ComponentModel.EditorBrowsableAttribute(EditorBrowsableState.Never)]
	public void OnDeserializing(StreamingContext context)
	{
		this.Initialize();
	}
}

[Table(Name="dbo.CondicionesReglasOperadorLogico")]
[DataContract()]
public partial class CondicionesReglasOperadorLogico : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private decimal _id;
	
	private string _NomOperadorLogico;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(decimal value);
    partial void OnidChanged();
    partial void OnNomOperadorLogicoChanging(string value);
    partial void OnNomOperadorLogicoChanged();
    #endregion
	
	public CondicionesReglasOperadorLogico()
	{
		this.Initialize();
	}
	
	[Column(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Decimal(18,0) NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	[DataMember(Order=1)]
	public decimal id
	{
		get
		{
			return this._id;
		}
		set
		{
			if ((this._id != value))
			{
				this.OnidChanging(value);
				this.SendPropertyChanging();
				this._id = value;
				this.SendPropertyChanged("id");
				this.OnidChanged();
			}
		}
	}
	
	[Column(Storage="_NomOperadorLogico", DbType="VarChar(50)")]
	[DataMember(Order=2)]
	public string NomOperadorLogico
	{
		get
		{
			return this._NomOperadorLogico;
		}
		set
		{
			if ((this._NomOperadorLogico != value))
			{
				this.OnNomOperadorLogicoChanging(value);
				this.SendPropertyChanging();
				this._NomOperadorLogico = value;
				this.SendPropertyChanged("NomOperadorLogico");
				this.OnNomOperadorLogicoChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void Initialize()
	{
		OnCreated();
	}
	
	[OnDeserializing()]
	[System.ComponentModel.EditorBrowsableAttribute(EditorBrowsableState.Never)]
	public void OnDeserializing(StreamingContext context)
	{
		this.Initialize();
	}
}

[Table(Name="dbo.AttrReglasCondicion")]
[DataContract()]
public partial class AttrReglasCondicion : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private decimal _id;
	
	private System.Nullable<decimal> _idRegla;
	
	private System.Nullable<decimal> _AtributoID;
	
	private string _AtributoNom;
	
	private string _OpreradorAritmetico;
	
	private string _ValorAttr;
	
	private string _OperadorLogico;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(decimal value);
    partial void OnidChanged();
    partial void OnidReglaChanging(System.Nullable<decimal> value);
    partial void OnidReglaChanged();
    partial void OnAtributoIDChanging(System.Nullable<decimal> value);
    partial void OnAtributoIDChanged();
    partial void OnAtributoNomChanging(string value);
    partial void OnAtributoNomChanged();
    partial void OnOpreradorAritmeticoChanging(string value);
    partial void OnOpreradorAritmeticoChanged();
    partial void OnValorAttrChanging(string value);
    partial void OnValorAttrChanged();
    partial void OnOperadorLogicoChanging(string value);
    partial void OnOperadorLogicoChanged();
    #endregion
	
	public AttrReglasCondicion()
	{
		this.Initialize();
	}
	
	[Column(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Decimal(18,0) NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	[DataMember(Order=1)]
	public decimal id
	{
		get
		{
			return this._id;
		}
		set
		{
			if ((this._id != value))
			{
				this.OnidChanging(value);
				this.SendPropertyChanging();
				this._id = value;
				this.SendPropertyChanged("id");
				this.OnidChanged();
			}
		}
	}
	
	[Column(Storage="_idRegla", DbType="Decimal(18,0)")]
	[DataMember(Order=2)]
	public System.Nullable<decimal> idRegla
	{
		get
		{
			return this._idRegla;
		}
		set
		{
			if ((this._idRegla != value))
			{
				this.OnidReglaChanging(value);
				this.SendPropertyChanging();
				this._idRegla = value;
				this.SendPropertyChanged("idRegla");
				this.OnidReglaChanged();
			}
		}
	}
	
	[Column(Storage="_AtributoID", DbType="Decimal(18,0)")]
	[DataMember(Order=3)]
	public System.Nullable<decimal> AtributoID
	{
		get
		{
			return this._AtributoID;
		}
		set
		{
			if ((this._AtributoID != value))
			{
				this.OnAtributoIDChanging(value);
				this.SendPropertyChanging();
				this._AtributoID = value;
				this.SendPropertyChanged("AtributoID");
				this.OnAtributoIDChanged();
			}
		}
	}
	
	[Column(Storage="_AtributoNom", DbType="VarChar(50)")]
	[DataMember(Order=4)]
	public string AtributoNom
	{
		get
		{
			return this._AtributoNom;
		}
		set
		{
			if ((this._AtributoNom != value))
			{
				this.OnAtributoNomChanging(value);
				this.SendPropertyChanging();
				this._AtributoNom = value;
				this.SendPropertyChanged("AtributoNom");
				this.OnAtributoNomChanged();
			}
		}
	}
	
	[Column(Storage="_OpreradorAritmetico", DbType="VarChar(50)")]
	[DataMember(Order=5)]
	public string OpreradorAritmetico
	{
		get
		{
			return this._OpreradorAritmetico;
		}
		set
		{
			if ((this._OpreradorAritmetico != value))
			{
				this.OnOpreradorAritmeticoChanging(value);
				this.SendPropertyChanging();
				this._OpreradorAritmetico = value;
				this.SendPropertyChanged("OpreradorAritmetico");
				this.OnOpreradorAritmeticoChanged();
			}
		}
	}
	
	[Column(Storage="_ValorAttr", DbType="VarChar(50)")]
	[DataMember(Order=6)]
	public string ValorAttr
	{
		get
		{
			return this._ValorAttr;
		}
		set
		{
			if ((this._ValorAttr != value))
			{
				this.OnValorAttrChanging(value);
				this.SendPropertyChanging();
				this._ValorAttr = value;
				this.SendPropertyChanged("ValorAttr");
				this.OnValorAttrChanged();
			}
		}
	}
	
	[Column(Storage="_OperadorLogico", DbType="VarChar(50)")]
	[DataMember(Order=7)]
	public string OperadorLogico
	{
		get
		{
			return this._OperadorLogico;
		}
		set
		{
			if ((this._OperadorLogico != value))
			{
				this.OnOperadorLogicoChanging(value);
				this.SendPropertyChanging();
				this._OperadorLogico = value;
				this.SendPropertyChanged("OperadorLogico");
				this.OnOperadorLogicoChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void Initialize()
	{
		OnCreated();
	}
	
	[OnDeserializing()]
	[System.ComponentModel.EditorBrowsableAttribute(EditorBrowsableState.Never)]
	public void OnDeserializing(StreamingContext context)
	{
		this.Initialize();
	}
}

[Table(Name="dbo.AttrReglasAccion")]
[DataContract()]
public partial class AttrReglasAccion : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private decimal _id;
	
	private System.Nullable<decimal> _idCondicion;
	
	private System.Nullable<decimal> _idAtributo;
	
	private string _NomAtributo;
	
	private string _OpAritmetico;
	
	private string _Valor;
	
	private string _Mensaje;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(decimal value);
    partial void OnidChanged();
    partial void OnidCondicionChanging(System.Nullable<decimal> value);
    partial void OnidCondicionChanged();
    partial void OnidAtributoChanging(System.Nullable<decimal> value);
    partial void OnidAtributoChanged();
    partial void OnNomAtributoChanging(string value);
    partial void OnNomAtributoChanged();
    partial void OnOpAritmeticoChanging(string value);
    partial void OnOpAritmeticoChanged();
    partial void OnValorChanging(string value);
    partial void OnValorChanged();
    partial void OnMensajeChanging(string value);
    partial void OnMensajeChanged();
    #endregion
	
	public AttrReglasAccion()
	{
		this.Initialize();
	}
	
	[Column(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Decimal(18,0) NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	[DataMember(Order=1)]
	public decimal id
	{
		get
		{
			return this._id;
		}
		set
		{
			if ((this._id != value))
			{
				this.OnidChanging(value);
				this.SendPropertyChanging();
				this._id = value;
				this.SendPropertyChanged("id");
				this.OnidChanged();
			}
		}
	}
	
	[Column(Storage="_idCondicion", DbType="Decimal(18,0)")]
	[DataMember(Order=2)]
	public System.Nullable<decimal> idCondicion
	{
		get
		{
			return this._idCondicion;
		}
		set
		{
			if ((this._idCondicion != value))
			{
				this.OnidCondicionChanging(value);
				this.SendPropertyChanging();
				this._idCondicion = value;
				this.SendPropertyChanged("idCondicion");
				this.OnidCondicionChanged();
			}
		}
	}
	
	[Column(Storage="_idAtributo", DbType="Decimal(18,0)")]
	[DataMember(Order=3)]
	public System.Nullable<decimal> idAtributo
	{
		get
		{
			return this._idAtributo;
		}
		set
		{
			if ((this._idAtributo != value))
			{
				this.OnidAtributoChanging(value);
				this.SendPropertyChanging();
				this._idAtributo = value;
				this.SendPropertyChanged("idAtributo");
				this.OnidAtributoChanged();
			}
		}
	}
	
	[Column(Storage="_NomAtributo", DbType="VarChar(50)")]
	[DataMember(Order=4)]
	public string NomAtributo
	{
		get
		{
			return this._NomAtributo;
		}
		set
		{
			if ((this._NomAtributo != value))
			{
				this.OnNomAtributoChanging(value);
				this.SendPropertyChanging();
				this._NomAtributo = value;
				this.SendPropertyChanged("NomAtributo");
				this.OnNomAtributoChanged();
			}
		}
	}
	
	[Column(Storage="_OpAritmetico", DbType="VarChar(50)")]
	[DataMember(Order=5)]
	public string OpAritmetico
	{
		get
		{
			return this._OpAritmetico;
		}
		set
		{
			if ((this._OpAritmetico != value))
			{
				this.OnOpAritmeticoChanging(value);
				this.SendPropertyChanging();
				this._OpAritmetico = value;
				this.SendPropertyChanged("OpAritmetico");
				this.OnOpAritmeticoChanged();
			}
		}
	}
	
	[Column(Storage="_Valor", DbType="VarChar(50)")]
	[DataMember(Order=6)]
	public string Valor
	{
		get
		{
			return this._Valor;
		}
		set
		{
			if ((this._Valor != value))
			{
				this.OnValorChanging(value);
				this.SendPropertyChanging();
				this._Valor = value;
				this.SendPropertyChanged("Valor");
				this.OnValorChanged();
			}
		}
	}
	
	[Column(Storage="_Mensaje", DbType="VarChar(255)")]
	[DataMember(Order=7)]
	public string Mensaje
	{
		get
		{
			return this._Mensaje;
		}
		set
		{
			if ((this._Mensaje != value))
			{
				this.OnMensajeChanging(value);
				this.SendPropertyChanging();
				this._Mensaje = value;
				this.SendPropertyChanged("Mensaje");
				this.OnMensajeChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void Initialize()
	{
		OnCreated();
	}
	
	[OnDeserializing()]
	[System.ComponentModel.EditorBrowsableAttribute(EditorBrowsableState.Never)]
	public void OnDeserializing(StreamingContext context)
	{
		this.Initialize();
	}
}

[Table(Name="dbo.ProductoInformacionGeneral")]
[DataContract()]
public partial class ProductoInformacionGeneral : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _Id;
	
	private System.Nullable<int> _Identificador;
	
	private string _Autor;
	
	private System.Nullable<int> _Version;
	
	private System.Nullable<System.DateTime> _FechaCreacion;
	
	private System.Nullable<System.DateTime> _FechaVigenciaDesde;
	
	private System.Nullable<System.DateTime> _FechaVigenciaHasta;
	
	private string _Nombre;
	
	private string _Descripcion;
	
	private int _Familia;
	
	private string _Usuario;
	
	private string _Estado;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnIdentificadorChanging(System.Nullable<int> value);
    partial void OnIdentificadorChanged();
    partial void OnAutorChanging(string value);
    partial void OnAutorChanged();
    partial void OnVersionChanging(System.Nullable<int> value);
    partial void OnVersionChanged();
    partial void OnFechaCreacionChanging(System.Nullable<System.DateTime> value);
    partial void OnFechaCreacionChanged();
    partial void OnFechaVigenciaDesdeChanging(System.Nullable<System.DateTime> value);
    partial void OnFechaVigenciaDesdeChanged();
    partial void OnFechaVigenciaHastaChanging(System.Nullable<System.DateTime> value);
    partial void OnFechaVigenciaHastaChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnDescripcionChanging(string value);
    partial void OnDescripcionChanged();
    partial void OnFamiliaChanging(int value);
    partial void OnFamiliaChanged();
    partial void OnUsuarioChanging(string value);
    partial void OnUsuarioChanged();
    partial void OnEstadoChanging(string value);
    partial void OnEstadoChanged();
    #endregion
	
	public ProductoInformacionGeneral()
	{
		this.Initialize();
	}
	
	[Column(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	[DataMember(Order=1)]
	public int Id
	{
		get
		{
			return this._Id;
		}
		set
		{
			if ((this._Id != value))
			{
				this.OnIdChanging(value);
				this.SendPropertyChanging();
				this._Id = value;
				this.SendPropertyChanged("Id");
				this.OnIdChanged();
			}
		}
	}
	
	[Column(Storage="_Identificador", DbType="Int")]
	[DataMember(Order=2)]
	public System.Nullable<int> Identificador
	{
		get
		{
			return this._Identificador;
		}
		set
		{
			if ((this._Identificador != value))
			{
				this.OnIdentificadorChanging(value);
				this.SendPropertyChanging();
				this._Identificador = value;
				this.SendPropertyChanged("Identificador");
				this.OnIdentificadorChanged();
			}
		}
	}
	
	[Column(Storage="_Autor", DbType="VarChar(255)")]
	[DataMember(Order=3)]
	public string Autor
	{
		get
		{
			return this._Autor;
		}
		set
		{
			if ((this._Autor != value))
			{
				this.OnAutorChanging(value);
				this.SendPropertyChanging();
				this._Autor = value;
				this.SendPropertyChanged("Autor");
				this.OnAutorChanged();
			}
		}
	}
	
	[Column(Storage="_Version", DbType="Int")]
	[DataMember(Order=4)]
	public System.Nullable<int> Version
	{
		get
		{
			return this._Version;
		}
		set
		{
			if ((this._Version != value))
			{
				this.OnVersionChanging(value);
				this.SendPropertyChanging();
				this._Version = value;
				this.SendPropertyChanged("Version");
				this.OnVersionChanged();
			}
		}
	}
	
	[Column(Storage="_FechaCreacion", DbType="DateTime")]
	[DataMember(Order=5)]
	public System.Nullable<System.DateTime> FechaCreacion
	{
		get
		{
			return this._FechaCreacion;
		}
		set
		{
			if ((this._FechaCreacion != value))
			{
				this.OnFechaCreacionChanging(value);
				this.SendPropertyChanging();
				this._FechaCreacion = value;
				this.SendPropertyChanged("FechaCreacion");
				this.OnFechaCreacionChanged();
			}
		}
	}
	
	[Column(Storage="_FechaVigenciaDesde", DbType="DateTime")]
	[DataMember(Order=6)]
	public System.Nullable<System.DateTime> FechaVigenciaDesde
	{
		get
		{
			return this._FechaVigenciaDesde;
		}
		set
		{
			if ((this._FechaVigenciaDesde != value))
			{
				this.OnFechaVigenciaDesdeChanging(value);
				this.SendPropertyChanging();
				this._FechaVigenciaDesde = value;
				this.SendPropertyChanged("FechaVigenciaDesde");
				this.OnFechaVigenciaDesdeChanged();
			}
		}
	}
	
	[Column(Storage="_FechaVigenciaHasta", DbType="DateTime")]
	[DataMember(Order=7)]
	public System.Nullable<System.DateTime> FechaVigenciaHasta
	{
		get
		{
			return this._FechaVigenciaHasta;
		}
		set
		{
			if ((this._FechaVigenciaHasta != value))
			{
				this.OnFechaVigenciaHastaChanging(value);
				this.SendPropertyChanging();
				this._FechaVigenciaHasta = value;
				this.SendPropertyChanged("FechaVigenciaHasta");
				this.OnFechaVigenciaHastaChanged();
			}
		}
	}
	
	[Column(Storage="_Nombre", DbType="VarChar(100)")]
	[DataMember(Order=8)]
	public string Nombre
	{
		get
		{
			return this._Nombre;
		}
		set
		{
			if ((this._Nombre != value))
			{
				this.OnNombreChanging(value);
				this.SendPropertyChanging();
				this._Nombre = value;
				this.SendPropertyChanged("Nombre");
				this.OnNombreChanged();
			}
		}
	}
	
	[Column(Storage="_Descripcion", DbType="VarChar(1000)")]
	[DataMember(Order=9)]
	public string Descripcion
	{
		get
		{
			return this._Descripcion;
		}
		set
		{
			if ((this._Descripcion != value))
			{
				this.OnDescripcionChanging(value);
				this.SendPropertyChanging();
				this._Descripcion = value;
				this.SendPropertyChanged("Descripcion");
				this.OnDescripcionChanged();
			}
		}
	}
	
	[Column(Storage="_Familia", DbType="Int NOT NULL")]
	[DataMember(Order=10)]
	public int Familia
	{
		get
		{
			return this._Familia;
		}
		set
		{
			if ((this._Familia != value))
			{
				this.OnFamiliaChanging(value);
				this.SendPropertyChanging();
				this._Familia = value;
				this.SendPropertyChanged("Familia");
				this.OnFamiliaChanged();
			}
		}
	}
	
	[Column(Storage="_Usuario", DbType="VarChar(255)")]
	[DataMember(Order=11)]
	public string Usuario
	{
		get
		{
			return this._Usuario;
		}
		set
		{
			if ((this._Usuario != value))
			{
				this.OnUsuarioChanging(value);
				this.SendPropertyChanging();
				this._Usuario = value;
				this.SendPropertyChanged("Usuario");
				this.OnUsuarioChanged();
			}
		}
	}
	
	[Column(Storage="_Estado", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
	[DataMember(Order=12)]
	public string Estado
	{
		get
		{
			return this._Estado;
		}
		set
		{
			if ((this._Estado != value))
			{
				this.OnEstadoChanging(value);
				this.SendPropertyChanging();
				this._Estado = value;
				this.SendPropertyChanged("Estado");
				this.OnEstadoChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void Initialize()
	{
		OnCreated();
	}
	
	[OnDeserializing()]
	[System.ComponentModel.EditorBrowsableAttribute(EditorBrowsableState.Never)]
	public void OnDeserializing(StreamingContext context)
	{
		this.Initialize();
	}
}

[Table(Name="dbo.ProductoTarifa")]
[DataContract()]
public partial class ProductoTarifa : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _Id;
	
	private System.Nullable<int> _IdProducto;
	
	private string _Resolucion;
	
	private string _Observacion;
	
	private System.Nullable<int> _AdultosFemenino;
	
	private System.Nullable<int> _AdultosMasculino;
	
	private System.Nullable<int> _MayoresFemino;
	
	private System.Nullable<int> _MayoresMasculino;
	
	private System.Nullable<bool> _Bloquedo;
	
	private string _Usuario;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnIdProductoChanging(System.Nullable<int> value);
    partial void OnIdProductoChanged();
    partial void OnResolucionChanging(string value);
    partial void OnResolucionChanged();
    partial void OnObservacionChanging(string value);
    partial void OnObservacionChanged();
    partial void OnAdultosFemeninoChanging(System.Nullable<int> value);
    partial void OnAdultosFemeninoChanged();
    partial void OnAdultosMasculinoChanging(System.Nullable<int> value);
    partial void OnAdultosMasculinoChanged();
    partial void OnMayoresFeminoChanging(System.Nullable<int> value);
    partial void OnMayoresFeminoChanged();
    partial void OnMayoresMasculinoChanging(System.Nullable<int> value);
    partial void OnMayoresMasculinoChanged();
    partial void OnBloquedoChanging(System.Nullable<bool> value);
    partial void OnBloquedoChanged();
    partial void OnUsuarioChanging(string value);
    partial void OnUsuarioChanged();
    #endregion
	
	public ProductoTarifa()
	{
		this.Initialize();
	}
	
	[Column(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	[DataMember(Order=1)]
	public int Id
	{
		get
		{
			return this._Id;
		}
		set
		{
			if ((this._Id != value))
			{
				this.OnIdChanging(value);
				this.SendPropertyChanging();
				this._Id = value;
				this.SendPropertyChanged("Id");
				this.OnIdChanged();
			}
		}
	}
	
	[Column(Storage="_IdProducto", DbType="Int")]
	[DataMember(Order=2)]
	public System.Nullable<int> IdProducto
	{
		get
		{
			return this._IdProducto;
		}
		set
		{
			if ((this._IdProducto != value))
			{
				this.OnIdProductoChanging(value);
				this.SendPropertyChanging();
				this._IdProducto = value;
				this.SendPropertyChanged("IdProducto");
				this.OnIdProductoChanged();
			}
		}
	}
	
	[Column(Storage="_Resolucion", DbType="VarChar(255)")]
	[DataMember(Order=3)]
	public string Resolucion
	{
		get
		{
			return this._Resolucion;
		}
		set
		{
			if ((this._Resolucion != value))
			{
				this.OnResolucionChanging(value);
				this.SendPropertyChanging();
				this._Resolucion = value;
				this.SendPropertyChanged("Resolucion");
				this.OnResolucionChanged();
			}
		}
	}
	
	[Column(Storage="_Observacion", DbType="VarChar(1000)")]
	[DataMember(Order=4)]
	public string Observacion
	{
		get
		{
			return this._Observacion;
		}
		set
		{
			if ((this._Observacion != value))
			{
				this.OnObservacionChanging(value);
				this.SendPropertyChanging();
				this._Observacion = value;
				this.SendPropertyChanged("Observacion");
				this.OnObservacionChanged();
			}
		}
	}
	
	[Column(Storage="_AdultosFemenino", DbType="Int")]
	[DataMember(Order=5)]
	public System.Nullable<int> AdultosFemenino
	{
		get
		{
			return this._AdultosFemenino;
		}
		set
		{
			if ((this._AdultosFemenino != value))
			{
				this.OnAdultosFemeninoChanging(value);
				this.SendPropertyChanging();
				this._AdultosFemenino = value;
				this.SendPropertyChanged("AdultosFemenino");
				this.OnAdultosFemeninoChanged();
			}
		}
	}
	
	[Column(Storage="_AdultosMasculino", DbType="Int")]
	[DataMember(Order=6)]
	public System.Nullable<int> AdultosMasculino
	{
		get
		{
			return this._AdultosMasculino;
		}
		set
		{
			if ((this._AdultosMasculino != value))
			{
				this.OnAdultosMasculinoChanging(value);
				this.SendPropertyChanging();
				this._AdultosMasculino = value;
				this.SendPropertyChanged("AdultosMasculino");
				this.OnAdultosMasculinoChanged();
			}
		}
	}
	
	[Column(Storage="_MayoresFemino", DbType="Int")]
	[DataMember(Order=7)]
	public System.Nullable<int> MayoresFemino
	{
		get
		{
			return this._MayoresFemino;
		}
		set
		{
			if ((this._MayoresFemino != value))
			{
				this.OnMayoresFeminoChanging(value);
				this.SendPropertyChanging();
				this._MayoresFemino = value;
				this.SendPropertyChanged("MayoresFemino");
				this.OnMayoresFeminoChanged();
			}
		}
	}
	
	[Column(Storage="_MayoresMasculino", DbType="Int")]
	[DataMember(Order=8)]
	public System.Nullable<int> MayoresMasculino
	{
		get
		{
			return this._MayoresMasculino;
		}
		set
		{
			if ((this._MayoresMasculino != value))
			{
				this.OnMayoresMasculinoChanging(value);
				this.SendPropertyChanging();
				this._MayoresMasculino = value;
				this.SendPropertyChanged("MayoresMasculino");
				this.OnMayoresMasculinoChanged();
			}
		}
	}
	
	[Column(Storage="_Bloquedo", DbType="Bit")]
	[DataMember(Order=9)]
	public System.Nullable<bool> Bloquedo
	{
		get
		{
			return this._Bloquedo;
		}
		set
		{
			if ((this._Bloquedo != value))
			{
				this.OnBloquedoChanging(value);
				this.SendPropertyChanging();
				this._Bloquedo = value;
				this.SendPropertyChanged("Bloquedo");
				this.OnBloquedoChanged();
			}
		}
	}
	
	[Column(Storage="_Usuario", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
	[DataMember(Order=10)]
	public string Usuario
	{
		get
		{
			return this._Usuario;
		}
		set
		{
			if ((this._Usuario != value))
			{
				this.OnUsuarioChanging(value);
				this.SendPropertyChanging();
				this._Usuario = value;
				this.SendPropertyChanged("Usuario");
				this.OnUsuarioChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void Initialize()
	{
		OnCreated();
	}
	
	[OnDeserializing()]
	[System.ComponentModel.EditorBrowsableAttribute(EditorBrowsableState.Never)]
	public void OnDeserializing(StreamingContext context)
	{
		this.Initialize();
	}
}

[Table(Name="dbo.ProductoRevision")]
[DataContract()]
public partial class ProductoRevision : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _Id;
	
	private System.Nullable<int> _IdProducto;
	
	private string _Resolucion;
	
	private string _Observacion;
	
	private System.Nullable<bool> _Bloquedo;
	
	private string _Usuario;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnIdProductoChanging(System.Nullable<int> value);
    partial void OnIdProductoChanged();
    partial void OnResolucionChanging(string value);
    partial void OnResolucionChanged();
    partial void OnObservacionChanging(string value);
    partial void OnObservacionChanged();
    partial void OnBloquedoChanging(System.Nullable<bool> value);
    partial void OnBloquedoChanged();
    partial void OnUsuarioChanging(string value);
    partial void OnUsuarioChanged();
    #endregion
	
	public ProductoRevision()
	{
		this.Initialize();
	}
	
	[Column(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	[DataMember(Order=1)]
	public int Id
	{
		get
		{
			return this._Id;
		}
		set
		{
			if ((this._Id != value))
			{
				this.OnIdChanging(value);
				this.SendPropertyChanging();
				this._Id = value;
				this.SendPropertyChanged("Id");
				this.OnIdChanged();
			}
		}
	}
	
	[Column(Storage="_IdProducto", DbType="Int")]
	[DataMember(Order=2)]
	public System.Nullable<int> IdProducto
	{
		get
		{
			return this._IdProducto;
		}
		set
		{
			if ((this._IdProducto != value))
			{
				this.OnIdProductoChanging(value);
				this.SendPropertyChanging();
				this._IdProducto = value;
				this.SendPropertyChanged("IdProducto");
				this.OnIdProductoChanged();
			}
		}
	}
	
	[Column(Storage="_Resolucion", DbType="VarChar(255)")]
	[DataMember(Order=3)]
	public string Resolucion
	{
		get
		{
			return this._Resolucion;
		}
		set
		{
			if ((this._Resolucion != value))
			{
				this.OnResolucionChanging(value);
				this.SendPropertyChanging();
				this._Resolucion = value;
				this.SendPropertyChanged("Resolucion");
				this.OnResolucionChanged();
			}
		}
	}
	
	[Column(Storage="_Observacion", DbType="VarChar(1000)")]
	[DataMember(Order=4)]
	public string Observacion
	{
		get
		{
			return this._Observacion;
		}
		set
		{
			if ((this._Observacion != value))
			{
				this.OnObservacionChanging(value);
				this.SendPropertyChanging();
				this._Observacion = value;
				this.SendPropertyChanged("Observacion");
				this.OnObservacionChanged();
			}
		}
	}
	
	[Column(Storage="_Bloquedo", DbType="Bit")]
	[DataMember(Order=5)]
	public System.Nullable<bool> Bloquedo
	{
		get
		{
			return this._Bloquedo;
		}
		set
		{
			if ((this._Bloquedo != value))
			{
				this.OnBloquedoChanging(value);
				this.SendPropertyChanging();
				this._Bloquedo = value;
				this.SendPropertyChanged("Bloquedo");
				this.OnBloquedoChanged();
			}
		}
	}
	
	[Column(Storage="_Usuario", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
	[DataMember(Order=6)]
	public string Usuario
	{
		get
		{
			return this._Usuario;
		}
		set
		{
			if ((this._Usuario != value))
			{
				this.OnUsuarioChanging(value);
				this.SendPropertyChanging();
				this._Usuario = value;
				this.SendPropertyChanged("Usuario");
				this.OnUsuarioChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void Initialize()
	{
		OnCreated();
	}
	
	[OnDeserializing()]
	[System.ComponentModel.EditorBrowsableAttribute(EditorBrowsableState.Never)]
	public void OnDeserializing(StreamingContext context)
	{
		this.Initialize();
	}
}

[Table(Name="dbo.ProductoEstructuraAttr")]
[DataContract()]
public partial class ProductoEstructuraAttr : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private decimal _id;
	
	private decimal _idProducto;
	
	private decimal _idFamilia;
	
	private decimal _idAtributo;
	
	private string _NomAtributo;
	
	private string _TipoAtributo;
	
	private string _ValorAtributo;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(decimal value);
    partial void OnidChanged();
    partial void OnidProductoChanging(decimal value);
    partial void OnidProductoChanged();
    partial void OnidFamiliaChanging(decimal value);
    partial void OnidFamiliaChanged();
    partial void OnidAtributoChanging(decimal value);
    partial void OnidAtributoChanged();
    partial void OnNomAtributoChanging(string value);
    partial void OnNomAtributoChanged();
    partial void OnTipoAtributoChanging(string value);
    partial void OnTipoAtributoChanged();
    partial void OnValorAtributoChanging(string value);
    partial void OnValorAtributoChanged();
    #endregion
	
	public ProductoEstructuraAttr()
	{
		this.Initialize();
	}
	
	[Column(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Decimal(18,0) NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	[DataMember(Order=1)]
	public decimal id
	{
		get
		{
			return this._id;
		}
		set
		{
			if ((this._id != value))
			{
				this.OnidChanging(value);
				this.SendPropertyChanging();
				this._id = value;
				this.SendPropertyChanged("id");
				this.OnidChanged();
			}
		}
	}
	
	[Column(Storage="_idProducto", DbType="Decimal(18,0) NOT NULL", IsPrimaryKey=true)]
	[DataMember(Order=2)]
	public decimal idProducto
	{
		get
		{
			return this._idProducto;
		}
		set
		{
			if ((this._idProducto != value))
			{
				this.OnidProductoChanging(value);
				this.SendPropertyChanging();
				this._idProducto = value;
				this.SendPropertyChanged("idProducto");
				this.OnidProductoChanged();
			}
		}
	}
	
	[Column(Storage="_idFamilia", DbType="Decimal(18,0) NOT NULL", IsPrimaryKey=true)]
	[DataMember(Order=3)]
	public decimal idFamilia
	{
		get
		{
			return this._idFamilia;
		}
		set
		{
			if ((this._idFamilia != value))
			{
				this.OnidFamiliaChanging(value);
				this.SendPropertyChanging();
				this._idFamilia = value;
				this.SendPropertyChanged("idFamilia");
				this.OnidFamiliaChanged();
			}
		}
	}
	
	[Column(Storage="_idAtributo", DbType="Decimal(18,0) NOT NULL", IsPrimaryKey=true)]
	[DataMember(Order=4)]
	public decimal idAtributo
	{
		get
		{
			return this._idAtributo;
		}
		set
		{
			if ((this._idAtributo != value))
			{
				this.OnidAtributoChanging(value);
				this.SendPropertyChanging();
				this._idAtributo = value;
				this.SendPropertyChanged("idAtributo");
				this.OnidAtributoChanged();
			}
		}
	}
	
	[Column(Storage="_NomAtributo", DbType="VarChar(50)")]
	[DataMember(Order=5)]
	public string NomAtributo
	{
		get
		{
			return this._NomAtributo;
		}
		set
		{
			if ((this._NomAtributo != value))
			{
				this.OnNomAtributoChanging(value);
				this.SendPropertyChanging();
				this._NomAtributo = value;
				this.SendPropertyChanged("NomAtributo");
				this.OnNomAtributoChanged();
			}
		}
	}
	
	[Column(Storage="_TipoAtributo", DbType="VarChar(50)")]
	[DataMember(Order=6)]
	public string TipoAtributo
	{
		get
		{
			return this._TipoAtributo;
		}
		set
		{
			if ((this._TipoAtributo != value))
			{
				this.OnTipoAtributoChanging(value);
				this.SendPropertyChanging();
				this._TipoAtributo = value;
				this.SendPropertyChanged("TipoAtributo");
				this.OnTipoAtributoChanged();
			}
		}
	}
	
	[Column(Storage="_ValorAtributo", DbType="VarChar(50)")]
	[DataMember(Order=7)]
	public string ValorAtributo
	{
		get
		{
			return this._ValorAtributo;
		}
		set
		{
			if ((this._ValorAtributo != value))
			{
				this.OnValorAtributoChanging(value);
				this.SendPropertyChanging();
				this._ValorAtributo = value;
				this.SendPropertyChanged("ValorAtributo");
				this.OnValorAtributoChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void Initialize()
	{
		OnCreated();
	}
	
	[OnDeserializing()]
	[System.ComponentModel.EditorBrowsableAttribute(EditorBrowsableState.Never)]
	public void OnDeserializing(StreamingContext context)
	{
		this.Initialize();
	}
}
#pragma warning restore 1591
