//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión del motor en tiempo de ejecución:2.0.50727.3603
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.ServiceReference, version 2.0.5.0
// 
namespace SLAttr.DBService {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AtributoInformacionGeneral", Namespace="http://schemas.datacontract.org/2004/07/")]
    public partial class AtributoInformacionGeneral : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int IdField;
        
        private System.Nullable<int> IdentificadorField;
        
        private string AutorField;
        
        private System.Nullable<int> VersionField;
        
        private System.Nullable<System.DateTime> FechaCreacionField;
        
        private System.Nullable<System.DateTime> FechaVigenciaDesdeField;
        
        private System.Nullable<System.DateTime> FechaVigenciaHastaField;
        
        private string NombreField;
        
        private string DescripcionField;
        
        private System.Nullable<byte> EsModificableField;
        
        private System.Collections.ObjectModel.ObservableCollection<SLAttr.DBService.FamiliaAtributo> FamiliaAtributoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Identificador {
            get {
                return this.IdentificadorField;
            }
            set {
                if ((this.IdentificadorField.Equals(value) != true)) {
                    this.IdentificadorField = value;
                    this.RaisePropertyChanged("Identificador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string Autor {
            get {
                return this.AutorField;
            }
            set {
                if ((object.ReferenceEquals(this.AutorField, value) != true)) {
                    this.AutorField = value;
                    this.RaisePropertyChanged("Autor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public System.Nullable<int> Version {
            get {
                return this.VersionField;
            }
            set {
                if ((this.VersionField.Equals(value) != true)) {
                    this.VersionField = value;
                    this.RaisePropertyChanged("Version");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public System.Nullable<System.DateTime> FechaCreacion {
            get {
                return this.FechaCreacionField;
            }
            set {
                if ((this.FechaCreacionField.Equals(value) != true)) {
                    this.FechaCreacionField = value;
                    this.RaisePropertyChanged("FechaCreacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public System.Nullable<System.DateTime> FechaVigenciaDesde {
            get {
                return this.FechaVigenciaDesdeField;
            }
            set {
                if ((this.FechaVigenciaDesdeField.Equals(value) != true)) {
                    this.FechaVigenciaDesdeField = value;
                    this.RaisePropertyChanged("FechaVigenciaDesde");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public System.Nullable<System.DateTime> FechaVigenciaHasta {
            get {
                return this.FechaVigenciaHastaField;
            }
            set {
                if ((this.FechaVigenciaHastaField.Equals(value) != true)) {
                    this.FechaVigenciaHastaField = value;
                    this.RaisePropertyChanged("FechaVigenciaHasta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public System.Nullable<byte> EsModificable {
            get {
                return this.EsModificableField;
            }
            set {
                if ((this.EsModificableField.Equals(value) != true)) {
                    this.EsModificableField = value;
                    this.RaisePropertyChanged("EsModificable");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public System.Collections.ObjectModel.ObservableCollection<SLAttr.DBService.FamiliaAtributo> FamiliaAtributo {
            get {
                return this.FamiliaAtributoField;
            }
            set {
                if ((object.ReferenceEquals(this.FamiliaAtributoField, value) != true)) {
                    this.FamiliaAtributoField = value;
                    this.RaisePropertyChanged("FamiliaAtributo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FamiliaAtributo", Namespace="http://schemas.datacontract.org/2004/07/")]
    public partial class FamiliaAtributo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private System.Nullable<int> idFamiliaField;
        
        private System.Nullable<int> idAtributoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> idFamilia {
            get {
                return this.idFamiliaField;
            }
            set {
                if ((this.idFamiliaField.Equals(value) != true)) {
                    this.idFamiliaField = value;
                    this.RaisePropertyChanged("idFamilia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.Nullable<int> idAtributo {
            get {
                return this.idAtributoField;
            }
            set {
                if ((this.idAtributoField.Equals(value) != true)) {
                    this.idAtributoField = value;
                    this.RaisePropertyChanged("idAtributo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="", ConfigurationName="DBService.DBService2")]
    public interface DBService2 {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:DBService2/GetAtributoPorID", ReplyAction="urn:DBService2/GetAtributoPorIDResponse")]
        System.IAsyncResult BeginGetAtributoPorID(int pAttr, System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<SLAttr.DBService.AtributoInformacionGeneral> EndGetAtributoPorID(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:DBService2/GetAtributoPorNombre", ReplyAction="urn:DBService2/GetAtributoPorNombreResponse")]
        System.IAsyncResult BeginGetAtributoPorNombre(string pNom, System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<SLAttr.DBService.AtributoInformacionGeneral> EndGetAtributoPorNombre(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:DBService2/SaveAttrFlia", ReplyAction="urn:DBService2/SaveAttrFliaResponse")]
        System.IAsyncResult BeginSaveAttrFlia(System.Collections.ObjectModel.ObservableCollection<SLAttr.DBService.AtributoInformacionGeneral> list, int pflia, System.AsyncCallback callback, object asyncState);
        
        void EndSaveAttrFlia(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:DBService2/DeleteFlia", ReplyAction="urn:DBService2/DeleteFliaResponse")]
        System.IAsyncResult BeginDeleteFlia(int pflia, System.AsyncCallback callback, object asyncState);
        
        void EndDeleteFlia(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:DBService2/GetFlia", ReplyAction="urn:DBService2/GetFliaResponse")]
        System.IAsyncResult BeginGetFlia(int pFlia, System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<SLAttr.DBService.FamiliaAtributo> EndGetFlia(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:DBService2/GetFliaUltimoID", ReplyAction="urn:DBService2/GetFliaUltimoIDResponse")]
        System.IAsyncResult BeginGetFliaUltimoID(string pNombre, System.AsyncCallback callback, object asyncState);
        
        decimal EndGetFliaUltimoID(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface DBService2Channel : SLAttr.DBService.DBService2, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class GetAtributoPorIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetAtributoPorIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<SLAttr.DBService.AtributoInformacionGeneral> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<SLAttr.DBService.AtributoInformacionGeneral>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class GetAtributoPorNombreCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetAtributoPorNombreCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<SLAttr.DBService.AtributoInformacionGeneral> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<SLAttr.DBService.AtributoInformacionGeneral>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class GetFliaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetFliaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<SLAttr.DBService.FamiliaAtributo> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<SLAttr.DBService.FamiliaAtributo>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class GetFliaUltimoIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetFliaUltimoIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public decimal Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((decimal)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class DBService2Client : System.ServiceModel.ClientBase<SLAttr.DBService.DBService2>, SLAttr.DBService.DBService2 {
        
        private BeginOperationDelegate onBeginGetAtributoPorIDDelegate;
        
        private EndOperationDelegate onEndGetAtributoPorIDDelegate;
        
        private System.Threading.SendOrPostCallback onGetAtributoPorIDCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetAtributoPorNombreDelegate;
        
        private EndOperationDelegate onEndGetAtributoPorNombreDelegate;
        
        private System.Threading.SendOrPostCallback onGetAtributoPorNombreCompletedDelegate;
        
        private BeginOperationDelegate onBeginSaveAttrFliaDelegate;
        
        private EndOperationDelegate onEndSaveAttrFliaDelegate;
        
        private System.Threading.SendOrPostCallback onSaveAttrFliaCompletedDelegate;
        
        private BeginOperationDelegate onBeginDeleteFliaDelegate;
        
        private EndOperationDelegate onEndDeleteFliaDelegate;
        
        private System.Threading.SendOrPostCallback onDeleteFliaCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetFliaDelegate;
        
        private EndOperationDelegate onEndGetFliaDelegate;
        
        private System.Threading.SendOrPostCallback onGetFliaCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetFliaUltimoIDDelegate;
        
        private EndOperationDelegate onEndGetFliaUltimoIDDelegate;
        
        private System.Threading.SendOrPostCallback onGetFliaUltimoIDCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public DBService2Client() {
        }
        
        public DBService2Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DBService2Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DBService2Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DBService2Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<GetAtributoPorIDCompletedEventArgs> GetAtributoPorIDCompleted;
        
        public event System.EventHandler<GetAtributoPorNombreCompletedEventArgs> GetAtributoPorNombreCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> SaveAttrFliaCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> DeleteFliaCompleted;
        
        public event System.EventHandler<GetFliaCompletedEventArgs> GetFliaCompleted;
        
        public event System.EventHandler<GetFliaUltimoIDCompletedEventArgs> GetFliaUltimoIDCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult SLAttr.DBService.DBService2.BeginGetAtributoPorID(int pAttr, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetAtributoPorID(pAttr, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<SLAttr.DBService.AtributoInformacionGeneral> SLAttr.DBService.DBService2.EndGetAtributoPorID(System.IAsyncResult result) {
            return base.Channel.EndGetAtributoPorID(result);
        }
        
        private System.IAsyncResult OnBeginGetAtributoPorID(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int pAttr = ((int)(inValues[0]));
            return ((SLAttr.DBService.DBService2)(this)).BeginGetAtributoPorID(pAttr, callback, asyncState);
        }
        
        private object[] OnEndGetAtributoPorID(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<SLAttr.DBService.AtributoInformacionGeneral> retVal = ((SLAttr.DBService.DBService2)(this)).EndGetAtributoPorID(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetAtributoPorIDCompleted(object state) {
            if ((this.GetAtributoPorIDCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetAtributoPorIDCompleted(this, new GetAtributoPorIDCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetAtributoPorIDAsync(int pAttr) {
            this.GetAtributoPorIDAsync(pAttr, null);
        }
        
        public void GetAtributoPorIDAsync(int pAttr, object userState) {
            if ((this.onBeginGetAtributoPorIDDelegate == null)) {
                this.onBeginGetAtributoPorIDDelegate = new BeginOperationDelegate(this.OnBeginGetAtributoPorID);
            }
            if ((this.onEndGetAtributoPorIDDelegate == null)) {
                this.onEndGetAtributoPorIDDelegate = new EndOperationDelegate(this.OnEndGetAtributoPorID);
            }
            if ((this.onGetAtributoPorIDCompletedDelegate == null)) {
                this.onGetAtributoPorIDCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetAtributoPorIDCompleted);
            }
            base.InvokeAsync(this.onBeginGetAtributoPorIDDelegate, new object[] {
                        pAttr}, this.onEndGetAtributoPorIDDelegate, this.onGetAtributoPorIDCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult SLAttr.DBService.DBService2.BeginGetAtributoPorNombre(string pNom, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetAtributoPorNombre(pNom, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<SLAttr.DBService.AtributoInformacionGeneral> SLAttr.DBService.DBService2.EndGetAtributoPorNombre(System.IAsyncResult result) {
            return base.Channel.EndGetAtributoPorNombre(result);
        }
        
        private System.IAsyncResult OnBeginGetAtributoPorNombre(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string pNom = ((string)(inValues[0]));
            return ((SLAttr.DBService.DBService2)(this)).BeginGetAtributoPorNombre(pNom, callback, asyncState);
        }
        
        private object[] OnEndGetAtributoPorNombre(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<SLAttr.DBService.AtributoInformacionGeneral> retVal = ((SLAttr.DBService.DBService2)(this)).EndGetAtributoPorNombre(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetAtributoPorNombreCompleted(object state) {
            if ((this.GetAtributoPorNombreCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetAtributoPorNombreCompleted(this, new GetAtributoPorNombreCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetAtributoPorNombreAsync(string pNom) {
            this.GetAtributoPorNombreAsync(pNom, null);
        }
        
        public void GetAtributoPorNombreAsync(string pNom, object userState) {
            if ((this.onBeginGetAtributoPorNombreDelegate == null)) {
                this.onBeginGetAtributoPorNombreDelegate = new BeginOperationDelegate(this.OnBeginGetAtributoPorNombre);
            }
            if ((this.onEndGetAtributoPorNombreDelegate == null)) {
                this.onEndGetAtributoPorNombreDelegate = new EndOperationDelegate(this.OnEndGetAtributoPorNombre);
            }
            if ((this.onGetAtributoPorNombreCompletedDelegate == null)) {
                this.onGetAtributoPorNombreCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetAtributoPorNombreCompleted);
            }
            base.InvokeAsync(this.onBeginGetAtributoPorNombreDelegate, new object[] {
                        pNom}, this.onEndGetAtributoPorNombreDelegate, this.onGetAtributoPorNombreCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult SLAttr.DBService.DBService2.BeginSaveAttrFlia(System.Collections.ObjectModel.ObservableCollection<SLAttr.DBService.AtributoInformacionGeneral> list, int pflia, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginSaveAttrFlia(list, pflia, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void SLAttr.DBService.DBService2.EndSaveAttrFlia(System.IAsyncResult result) {
            base.Channel.EndSaveAttrFlia(result);
        }
        
        private System.IAsyncResult OnBeginSaveAttrFlia(object[] inValues, System.AsyncCallback callback, object asyncState) {
            System.Collections.ObjectModel.ObservableCollection<SLAttr.DBService.AtributoInformacionGeneral> list = ((System.Collections.ObjectModel.ObservableCollection<SLAttr.DBService.AtributoInformacionGeneral>)(inValues[0]));
            int pflia = ((int)(inValues[1]));
            return ((SLAttr.DBService.DBService2)(this)).BeginSaveAttrFlia(list, pflia, callback, asyncState);
        }
        
        private object[] OnEndSaveAttrFlia(System.IAsyncResult result) {
            ((SLAttr.DBService.DBService2)(this)).EndSaveAttrFlia(result);
            return null;
        }
        
        private void OnSaveAttrFliaCompleted(object state) {
            if ((this.SaveAttrFliaCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.SaveAttrFliaCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void SaveAttrFliaAsync(System.Collections.ObjectModel.ObservableCollection<SLAttr.DBService.AtributoInformacionGeneral> list, int pflia) {
            this.SaveAttrFliaAsync(list, pflia, null);
        }
        
        public void SaveAttrFliaAsync(System.Collections.ObjectModel.ObservableCollection<SLAttr.DBService.AtributoInformacionGeneral> list, int pflia, object userState) {
            if ((this.onBeginSaveAttrFliaDelegate == null)) {
                this.onBeginSaveAttrFliaDelegate = new BeginOperationDelegate(this.OnBeginSaveAttrFlia);
            }
            if ((this.onEndSaveAttrFliaDelegate == null)) {
                this.onEndSaveAttrFliaDelegate = new EndOperationDelegate(this.OnEndSaveAttrFlia);
            }
            if ((this.onSaveAttrFliaCompletedDelegate == null)) {
                this.onSaveAttrFliaCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnSaveAttrFliaCompleted);
            }
            base.InvokeAsync(this.onBeginSaveAttrFliaDelegate, new object[] {
                        list,
                        pflia}, this.onEndSaveAttrFliaDelegate, this.onSaveAttrFliaCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult SLAttr.DBService.DBService2.BeginDeleteFlia(int pflia, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginDeleteFlia(pflia, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void SLAttr.DBService.DBService2.EndDeleteFlia(System.IAsyncResult result) {
            base.Channel.EndDeleteFlia(result);
        }
        
        private System.IAsyncResult OnBeginDeleteFlia(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int pflia = ((int)(inValues[0]));
            return ((SLAttr.DBService.DBService2)(this)).BeginDeleteFlia(pflia, callback, asyncState);
        }
        
        private object[] OnEndDeleteFlia(System.IAsyncResult result) {
            ((SLAttr.DBService.DBService2)(this)).EndDeleteFlia(result);
            return null;
        }
        
        private void OnDeleteFliaCompleted(object state) {
            if ((this.DeleteFliaCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.DeleteFliaCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void DeleteFliaAsync(int pflia) {
            this.DeleteFliaAsync(pflia, null);
        }
        
        public void DeleteFliaAsync(int pflia, object userState) {
            if ((this.onBeginDeleteFliaDelegate == null)) {
                this.onBeginDeleteFliaDelegate = new BeginOperationDelegate(this.OnBeginDeleteFlia);
            }
            if ((this.onEndDeleteFliaDelegate == null)) {
                this.onEndDeleteFliaDelegate = new EndOperationDelegate(this.OnEndDeleteFlia);
            }
            if ((this.onDeleteFliaCompletedDelegate == null)) {
                this.onDeleteFliaCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnDeleteFliaCompleted);
            }
            base.InvokeAsync(this.onBeginDeleteFliaDelegate, new object[] {
                        pflia}, this.onEndDeleteFliaDelegate, this.onDeleteFliaCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult SLAttr.DBService.DBService2.BeginGetFlia(int pFlia, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetFlia(pFlia, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<SLAttr.DBService.FamiliaAtributo> SLAttr.DBService.DBService2.EndGetFlia(System.IAsyncResult result) {
            return base.Channel.EndGetFlia(result);
        }
        
        private System.IAsyncResult OnBeginGetFlia(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int pFlia = ((int)(inValues[0]));
            return ((SLAttr.DBService.DBService2)(this)).BeginGetFlia(pFlia, callback, asyncState);
        }
        
        private object[] OnEndGetFlia(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<SLAttr.DBService.FamiliaAtributo> retVal = ((SLAttr.DBService.DBService2)(this)).EndGetFlia(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetFliaCompleted(object state) {
            if ((this.GetFliaCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetFliaCompleted(this, new GetFliaCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetFliaAsync(int pFlia) {
            this.GetFliaAsync(pFlia, null);
        }
        
        public void GetFliaAsync(int pFlia, object userState) {
            if ((this.onBeginGetFliaDelegate == null)) {
                this.onBeginGetFliaDelegate = new BeginOperationDelegate(this.OnBeginGetFlia);
            }
            if ((this.onEndGetFliaDelegate == null)) {
                this.onEndGetFliaDelegate = new EndOperationDelegate(this.OnEndGetFlia);
            }
            if ((this.onGetFliaCompletedDelegate == null)) {
                this.onGetFliaCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetFliaCompleted);
            }
            base.InvokeAsync(this.onBeginGetFliaDelegate, new object[] {
                        pFlia}, this.onEndGetFliaDelegate, this.onGetFliaCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult SLAttr.DBService.DBService2.BeginGetFliaUltimoID(string pNombre, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetFliaUltimoID(pNombre, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        decimal SLAttr.DBService.DBService2.EndGetFliaUltimoID(System.IAsyncResult result) {
            return base.Channel.EndGetFliaUltimoID(result);
        }
        
        private System.IAsyncResult OnBeginGetFliaUltimoID(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string pNombre = ((string)(inValues[0]));
            return ((SLAttr.DBService.DBService2)(this)).BeginGetFliaUltimoID(pNombre, callback, asyncState);
        }
        
        private object[] OnEndGetFliaUltimoID(System.IAsyncResult result) {
            decimal retVal = ((SLAttr.DBService.DBService2)(this)).EndGetFliaUltimoID(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetFliaUltimoIDCompleted(object state) {
            if ((this.GetFliaUltimoIDCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetFliaUltimoIDCompleted(this, new GetFliaUltimoIDCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetFliaUltimoIDAsync(string pNombre) {
            this.GetFliaUltimoIDAsync(pNombre, null);
        }
        
        public void GetFliaUltimoIDAsync(string pNombre, object userState) {
            if ((this.onBeginGetFliaUltimoIDDelegate == null)) {
                this.onBeginGetFliaUltimoIDDelegate = new BeginOperationDelegate(this.OnBeginGetFliaUltimoID);
            }
            if ((this.onEndGetFliaUltimoIDDelegate == null)) {
                this.onEndGetFliaUltimoIDDelegate = new EndOperationDelegate(this.OnEndGetFliaUltimoID);
            }
            if ((this.onGetFliaUltimoIDCompletedDelegate == null)) {
                this.onGetFliaUltimoIDCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetFliaUltimoIDCompleted);
            }
            base.InvokeAsync(this.onBeginGetFliaUltimoIDDelegate, new object[] {
                        pNombre}, this.onEndGetFliaUltimoIDDelegate, this.onGetFliaUltimoIDCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override SLAttr.DBService.DBService2 CreateChannel() {
            return new DBService2ClientChannel(this);
        }
        
        private class DBService2ClientChannel : ChannelBase<SLAttr.DBService.DBService2>, SLAttr.DBService.DBService2 {
            
            public DBService2ClientChannel(System.ServiceModel.ClientBase<SLAttr.DBService.DBService2> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginGetAtributoPorID(int pAttr, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = pAttr;
                System.IAsyncResult _result = base.BeginInvoke("GetAtributoPorID", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.ObjectModel.ObservableCollection<SLAttr.DBService.AtributoInformacionGeneral> EndGetAtributoPorID(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<SLAttr.DBService.AtributoInformacionGeneral> _result = ((System.Collections.ObjectModel.ObservableCollection<SLAttr.DBService.AtributoInformacionGeneral>)(base.EndInvoke("GetAtributoPorID", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetAtributoPorNombre(string pNom, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = pNom;
                System.IAsyncResult _result = base.BeginInvoke("GetAtributoPorNombre", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.ObjectModel.ObservableCollection<SLAttr.DBService.AtributoInformacionGeneral> EndGetAtributoPorNombre(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<SLAttr.DBService.AtributoInformacionGeneral> _result = ((System.Collections.ObjectModel.ObservableCollection<SLAttr.DBService.AtributoInformacionGeneral>)(base.EndInvoke("GetAtributoPorNombre", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginSaveAttrFlia(System.Collections.ObjectModel.ObservableCollection<SLAttr.DBService.AtributoInformacionGeneral> list, int pflia, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[2];
                _args[0] = list;
                _args[1] = pflia;
                System.IAsyncResult _result = base.BeginInvoke("SaveAttrFlia", _args, callback, asyncState);
                return _result;
            }
            
            public void EndSaveAttrFlia(System.IAsyncResult result) {
                object[] _args = new object[0];
                base.EndInvoke("SaveAttrFlia", _args, result);
            }
            
            public System.IAsyncResult BeginDeleteFlia(int pflia, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = pflia;
                System.IAsyncResult _result = base.BeginInvoke("DeleteFlia", _args, callback, asyncState);
                return _result;
            }
            
            public void EndDeleteFlia(System.IAsyncResult result) {
                object[] _args = new object[0];
                base.EndInvoke("DeleteFlia", _args, result);
            }
            
            public System.IAsyncResult BeginGetFlia(int pFlia, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = pFlia;
                System.IAsyncResult _result = base.BeginInvoke("GetFlia", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.ObjectModel.ObservableCollection<SLAttr.DBService.FamiliaAtributo> EndGetFlia(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<SLAttr.DBService.FamiliaAtributo> _result = ((System.Collections.ObjectModel.ObservableCollection<SLAttr.DBService.FamiliaAtributo>)(base.EndInvoke("GetFlia", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetFliaUltimoID(string pNombre, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = pNombre;
                System.IAsyncResult _result = base.BeginInvoke("GetFliaUltimoID", _args, callback, asyncState);
                return _result;
            }
            
            public decimal EndGetFliaUltimoID(System.IAsyncResult result) {
                object[] _args = new object[0];
                decimal _result = ((decimal)(base.EndInvoke("GetFliaUltimoID", _args, result)));
                return _result;
            }
        }
    }
}
