//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión del motor en tiempo de ejecución:2.0.50727.3603
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.ServiceReference, version 2.0.5.0
// 
namespace AttrForm.DBService1 {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TreeNodos", Namespace="http://schemas.datacontract.org/2004/07/")]
    public partial class TreeNodos : object, System.ComponentModel.INotifyPropertyChanged {
        
        private decimal IDTreeField;
        
        private string NomTreeField;
        
        private System.Nullable<decimal> IDParentField;
        
        private System.Nullable<decimal> IDAttrField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal IDTree {
            get {
                return this.IDTreeField;
            }
            set {
                if ((this.IDTreeField.Equals(value) != true)) {
                    this.IDTreeField = value;
                    this.RaisePropertyChanged("IDTree");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NomTree {
            get {
                return this.NomTreeField;
            }
            set {
                if ((object.ReferenceEquals(this.NomTreeField, value) != true)) {
                    this.NomTreeField = value;
                    this.RaisePropertyChanged("NomTree");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.Nullable<decimal> IDParent {
            get {
                return this.IDParentField;
            }
            set {
                if ((this.IDParentField.Equals(value) != true)) {
                    this.IDParentField = value;
                    this.RaisePropertyChanged("IDParent");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public System.Nullable<decimal> IDAttr {
            get {
                return this.IDAttrField;
            }
            set {
                if ((this.IDAttrField.Equals(value) != true)) {
                    this.IDAttrField = value;
                    this.RaisePropertyChanged("IDAttr");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TreeEstructuraItems", Namespace="http://schemas.datacontract.org/2004/07/")]
    public partial class TreeEstructuraItems : object, System.ComponentModel.INotifyPropertyChanged {
        
        private decimal IDTreeEstructuraItemField;
        
        private System.Nullable<bool> EsRequeridoField;
        
        private System.Nullable<bool> SoloLecturaField;
        
        private System.Nullable<bool> MultiSeleccionField;
        
        private string SubTipoField;
        
        private string OrigenDeDatosField;
        
        private string ValoresField;
        
        private string RutaField;
        
        private string MetodoField;
        
        private string TipoField;
        
        private System.Nullable<decimal> LargoField;
        
        private System.Nullable<decimal> DecimalesField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal IDTreeEstructuraItem {
            get {
                return this.IDTreeEstructuraItemField;
            }
            set {
                if ((this.IDTreeEstructuraItemField.Equals(value) != true)) {
                    this.IDTreeEstructuraItemField = value;
                    this.RaisePropertyChanged("IDTreeEstructuraItem");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public System.Nullable<bool> EsRequerido {
            get {
                return this.EsRequeridoField;
            }
            set {
                if ((this.EsRequeridoField.Equals(value) != true)) {
                    this.EsRequeridoField = value;
                    this.RaisePropertyChanged("EsRequerido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.Nullable<bool> SoloLectura {
            get {
                return this.SoloLecturaField;
            }
            set {
                if ((this.SoloLecturaField.Equals(value) != true)) {
                    this.SoloLecturaField = value;
                    this.RaisePropertyChanged("SoloLectura");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public System.Nullable<bool> MultiSeleccion {
            get {
                return this.MultiSeleccionField;
            }
            set {
                if ((this.MultiSeleccionField.Equals(value) != true)) {
                    this.MultiSeleccionField = value;
                    this.RaisePropertyChanged("MultiSeleccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string SubTipo {
            get {
                return this.SubTipoField;
            }
            set {
                if ((object.ReferenceEquals(this.SubTipoField, value) != true)) {
                    this.SubTipoField = value;
                    this.RaisePropertyChanged("SubTipo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public string OrigenDeDatos {
            get {
                return this.OrigenDeDatosField;
            }
            set {
                if ((object.ReferenceEquals(this.OrigenDeDatosField, value) != true)) {
                    this.OrigenDeDatosField = value;
                    this.RaisePropertyChanged("OrigenDeDatos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public string Valores {
            get {
                return this.ValoresField;
            }
            set {
                if ((object.ReferenceEquals(this.ValoresField, value) != true)) {
                    this.ValoresField = value;
                    this.RaisePropertyChanged("Valores");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public string Ruta {
            get {
                return this.RutaField;
            }
            set {
                if ((object.ReferenceEquals(this.RutaField, value) != true)) {
                    this.RutaField = value;
                    this.RaisePropertyChanged("Ruta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public string Metodo {
            get {
                return this.MetodoField;
            }
            set {
                if ((object.ReferenceEquals(this.MetodoField, value) != true)) {
                    this.MetodoField = value;
                    this.RaisePropertyChanged("Metodo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public string Tipo {
            get {
                return this.TipoField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoField, value) != true)) {
                    this.TipoField = value;
                    this.RaisePropertyChanged("Tipo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=10)]
        public System.Nullable<decimal> Largo {
            get {
                return this.LargoField;
            }
            set {
                if ((this.LargoField.Equals(value) != true)) {
                    this.LargoField = value;
                    this.RaisePropertyChanged("Largo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=11)]
        public System.Nullable<decimal> Decimales {
            get {
                return this.DecimalesField;
            }
            set {
                if ((this.DecimalesField.Equals(value) != true)) {
                    this.DecimalesField = value;
                    this.RaisePropertyChanged("Decimales");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="", ConfigurationName="DBService1.DBService")]
    public interface DBService {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:DBService/SaveNode", ReplyAction="urn:DBService/SaveNodeResponse")]
        System.IAsyncResult BeginSaveNode(int pIDParent, int pIDatt, string pName, System.AsyncCallback callback, object asyncState);
        
        decimal EndSaveNode(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:DBService/GetTree", ReplyAction="urn:DBService/GetTreeResponse")]
        System.IAsyncResult BeginGetTree(int pAttr, System.AsyncCallback callback, object asyncState);
        
        AttrForm.DBService1.TreeNodos[] EndGetTree(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:DBService/GetItem", ReplyAction="urn:DBService/GetItemResponse")]
        System.IAsyncResult BeginGetItem(int pIdNodo, System.AsyncCallback callback, object asyncState);
        
        AttrForm.DBService1.TreeEstructuraItems[] EndGetItem(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:DBService/SaveNodeEstructure", ReplyAction="urn:DBService/SaveNodeEstructureResponse")]
        System.IAsyncResult BeginSaveNodeEstructure(int pIDTree, bool pEsReq, bool pSolol, bool pMulti, string pSubTipo, string pOrigDatos, string pValores, string pRuta, string pMetodo, string pTipo, int pLargo, int pDec, System.AsyncCallback callback, object asyncState);
        
        void EndSaveNodeEstructure(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface DBServiceChannel : AttrForm.DBService1.DBService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class SaveNodeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public SaveNodeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public decimal Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((decimal)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class GetTreeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetTreeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public AttrForm.DBService1.TreeNodos[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((AttrForm.DBService1.TreeNodos[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class GetItemCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetItemCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public AttrForm.DBService1.TreeEstructuraItems[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((AttrForm.DBService1.TreeEstructuraItems[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class DBServiceClient : System.ServiceModel.ClientBase<AttrForm.DBService1.DBService>, AttrForm.DBService1.DBService {
        
        private BeginOperationDelegate onBeginSaveNodeDelegate;
        
        private EndOperationDelegate onEndSaveNodeDelegate;
        
        private System.Threading.SendOrPostCallback onSaveNodeCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetTreeDelegate;
        
        private EndOperationDelegate onEndGetTreeDelegate;
        
        private System.Threading.SendOrPostCallback onGetTreeCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetItemDelegate;
        
        private EndOperationDelegate onEndGetItemDelegate;
        
        private System.Threading.SendOrPostCallback onGetItemCompletedDelegate;
        
        private BeginOperationDelegate onBeginSaveNodeEstructureDelegate;
        
        private EndOperationDelegate onEndSaveNodeEstructureDelegate;
        
        private System.Threading.SendOrPostCallback onSaveNodeEstructureCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public DBServiceClient() {
        }
        
        public DBServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DBServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DBServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DBServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<SaveNodeCompletedEventArgs> SaveNodeCompleted;
        
        public event System.EventHandler<GetTreeCompletedEventArgs> GetTreeCompleted;
        
        public event System.EventHandler<GetItemCompletedEventArgs> GetItemCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> SaveNodeEstructureCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult AttrForm.DBService1.DBService.BeginSaveNode(int pIDParent, int pIDatt, string pName, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginSaveNode(pIDParent, pIDatt, pName, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        decimal AttrForm.DBService1.DBService.EndSaveNode(System.IAsyncResult result) {
            return base.Channel.EndSaveNode(result);
        }
        
        private System.IAsyncResult OnBeginSaveNode(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int pIDParent = ((int)(inValues[0]));
            int pIDatt = ((int)(inValues[1]));
            string pName = ((string)(inValues[2]));
            return ((AttrForm.DBService1.DBService)(this)).BeginSaveNode(pIDParent, pIDatt, pName, callback, asyncState);
        }
        
        private object[] OnEndSaveNode(System.IAsyncResult result) {
            decimal retVal = ((AttrForm.DBService1.DBService)(this)).EndSaveNode(result);
            return new object[] {
                    retVal};
        }
        
        private void OnSaveNodeCompleted(object state) {
            if ((this.SaveNodeCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.SaveNodeCompleted(this, new SaveNodeCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void SaveNodeAsync(int pIDParent, int pIDatt, string pName) {
            this.SaveNodeAsync(pIDParent, pIDatt, pName, null);
        }
        
        public void SaveNodeAsync(int pIDParent, int pIDatt, string pName, object userState) {
            if ((this.onBeginSaveNodeDelegate == null)) {
                this.onBeginSaveNodeDelegate = new BeginOperationDelegate(this.OnBeginSaveNode);
            }
            if ((this.onEndSaveNodeDelegate == null)) {
                this.onEndSaveNodeDelegate = new EndOperationDelegate(this.OnEndSaveNode);
            }
            if ((this.onSaveNodeCompletedDelegate == null)) {
                this.onSaveNodeCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnSaveNodeCompleted);
            }
            base.InvokeAsync(this.onBeginSaveNodeDelegate, new object[] {
                        pIDParent,
                        pIDatt,
                        pName}, this.onEndSaveNodeDelegate, this.onSaveNodeCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult AttrForm.DBService1.DBService.BeginGetTree(int pAttr, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetTree(pAttr, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AttrForm.DBService1.TreeNodos[] AttrForm.DBService1.DBService.EndGetTree(System.IAsyncResult result) {
            return base.Channel.EndGetTree(result);
        }
        
        private System.IAsyncResult OnBeginGetTree(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int pAttr = ((int)(inValues[0]));
            return ((AttrForm.DBService1.DBService)(this)).BeginGetTree(pAttr, callback, asyncState);
        }
        
        private object[] OnEndGetTree(System.IAsyncResult result) {
            AttrForm.DBService1.TreeNodos[] retVal = ((AttrForm.DBService1.DBService)(this)).EndGetTree(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetTreeCompleted(object state) {
            if ((this.GetTreeCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetTreeCompleted(this, new GetTreeCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetTreeAsync(int pAttr) {
            this.GetTreeAsync(pAttr, null);
        }
        
        public void GetTreeAsync(int pAttr, object userState) {
            if ((this.onBeginGetTreeDelegate == null)) {
                this.onBeginGetTreeDelegate = new BeginOperationDelegate(this.OnBeginGetTree);
            }
            if ((this.onEndGetTreeDelegate == null)) {
                this.onEndGetTreeDelegate = new EndOperationDelegate(this.OnEndGetTree);
            }
            if ((this.onGetTreeCompletedDelegate == null)) {
                this.onGetTreeCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetTreeCompleted);
            }
            base.InvokeAsync(this.onBeginGetTreeDelegate, new object[] {
                        pAttr}, this.onEndGetTreeDelegate, this.onGetTreeCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult AttrForm.DBService1.DBService.BeginGetItem(int pIdNodo, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetItem(pIdNodo, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AttrForm.DBService1.TreeEstructuraItems[] AttrForm.DBService1.DBService.EndGetItem(System.IAsyncResult result) {
            return base.Channel.EndGetItem(result);
        }
        
        private System.IAsyncResult OnBeginGetItem(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int pIdNodo = ((int)(inValues[0]));
            return ((AttrForm.DBService1.DBService)(this)).BeginGetItem(pIdNodo, callback, asyncState);
        }
        
        private object[] OnEndGetItem(System.IAsyncResult result) {
            AttrForm.DBService1.TreeEstructuraItems[] retVal = ((AttrForm.DBService1.DBService)(this)).EndGetItem(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetItemCompleted(object state) {
            if ((this.GetItemCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetItemCompleted(this, new GetItemCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetItemAsync(int pIdNodo) {
            this.GetItemAsync(pIdNodo, null);
        }
        
        public void GetItemAsync(int pIdNodo, object userState) {
            if ((this.onBeginGetItemDelegate == null)) {
                this.onBeginGetItemDelegate = new BeginOperationDelegate(this.OnBeginGetItem);
            }
            if ((this.onEndGetItemDelegate == null)) {
                this.onEndGetItemDelegate = new EndOperationDelegate(this.OnEndGetItem);
            }
            if ((this.onGetItemCompletedDelegate == null)) {
                this.onGetItemCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetItemCompleted);
            }
            base.InvokeAsync(this.onBeginGetItemDelegate, new object[] {
                        pIdNodo}, this.onEndGetItemDelegate, this.onGetItemCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult AttrForm.DBService1.DBService.BeginSaveNodeEstructure(int pIDTree, bool pEsReq, bool pSolol, bool pMulti, string pSubTipo, string pOrigDatos, string pValores, string pRuta, string pMetodo, string pTipo, int pLargo, int pDec, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginSaveNodeEstructure(pIDTree, pEsReq, pSolol, pMulti, pSubTipo, pOrigDatos, pValores, pRuta, pMetodo, pTipo, pLargo, pDec, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void AttrForm.DBService1.DBService.EndSaveNodeEstructure(System.IAsyncResult result) {
            base.Channel.EndSaveNodeEstructure(result);
        }
        
        private System.IAsyncResult OnBeginSaveNodeEstructure(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int pIDTree = ((int)(inValues[0]));
            bool pEsReq = ((bool)(inValues[1]));
            bool pSolol = ((bool)(inValues[2]));
            bool pMulti = ((bool)(inValues[3]));
            string pSubTipo = ((string)(inValues[4]));
            string pOrigDatos = ((string)(inValues[5]));
            string pValores = ((string)(inValues[6]));
            string pRuta = ((string)(inValues[7]));
            string pMetodo = ((string)(inValues[8]));
            string pTipo = ((string)(inValues[9]));
            int pLargo = ((int)(inValues[10]));
            int pDec = ((int)(inValues[11]));
            return ((AttrForm.DBService1.DBService)(this)).BeginSaveNodeEstructure(pIDTree, pEsReq, pSolol, pMulti, pSubTipo, pOrigDatos, pValores, pRuta, pMetodo, pTipo, pLargo, pDec, callback, asyncState);
        }
        
        private object[] OnEndSaveNodeEstructure(System.IAsyncResult result) {
            ((AttrForm.DBService1.DBService)(this)).EndSaveNodeEstructure(result);
            return null;
        }
        
        private void OnSaveNodeEstructureCompleted(object state) {
            if ((this.SaveNodeEstructureCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.SaveNodeEstructureCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void SaveNodeEstructureAsync(int pIDTree, bool pEsReq, bool pSolol, bool pMulti, string pSubTipo, string pOrigDatos, string pValores, string pRuta, string pMetodo, string pTipo, int pLargo, int pDec) {
            this.SaveNodeEstructureAsync(pIDTree, pEsReq, pSolol, pMulti, pSubTipo, pOrigDatos, pValores, pRuta, pMetodo, pTipo, pLargo, pDec, null);
        }
        
        public void SaveNodeEstructureAsync(int pIDTree, bool pEsReq, bool pSolol, bool pMulti, string pSubTipo, string pOrigDatos, string pValores, string pRuta, string pMetodo, string pTipo, int pLargo, int pDec, object userState) {
            if ((this.onBeginSaveNodeEstructureDelegate == null)) {
                this.onBeginSaveNodeEstructureDelegate = new BeginOperationDelegate(this.OnBeginSaveNodeEstructure);
            }
            if ((this.onEndSaveNodeEstructureDelegate == null)) {
                this.onEndSaveNodeEstructureDelegate = new EndOperationDelegate(this.OnEndSaveNodeEstructure);
            }
            if ((this.onSaveNodeEstructureCompletedDelegate == null)) {
                this.onSaveNodeEstructureCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnSaveNodeEstructureCompleted);
            }
            base.InvokeAsync(this.onBeginSaveNodeEstructureDelegate, new object[] {
                        pIDTree,
                        pEsReq,
                        pSolol,
                        pMulti,
                        pSubTipo,
                        pOrigDatos,
                        pValores,
                        pRuta,
                        pMetodo,
                        pTipo,
                        pLargo,
                        pDec}, this.onEndSaveNodeEstructureDelegate, this.onSaveNodeEstructureCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override AttrForm.DBService1.DBService CreateChannel() {
            return new DBServiceClientChannel(this);
        }
        
        private class DBServiceClientChannel : ChannelBase<AttrForm.DBService1.DBService>, AttrForm.DBService1.DBService {
            
            public DBServiceClientChannel(System.ServiceModel.ClientBase<AttrForm.DBService1.DBService> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginSaveNode(int pIDParent, int pIDatt, string pName, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[3];
                _args[0] = pIDParent;
                _args[1] = pIDatt;
                _args[2] = pName;
                System.IAsyncResult _result = base.BeginInvoke("SaveNode", _args, callback, asyncState);
                return _result;
            }
            
            public decimal EndSaveNode(System.IAsyncResult result) {
                object[] _args = new object[0];
                decimal _result = ((decimal)(base.EndInvoke("SaveNode", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetTree(int pAttr, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = pAttr;
                System.IAsyncResult _result = base.BeginInvoke("GetTree", _args, callback, asyncState);
                return _result;
            }
            
            public AttrForm.DBService1.TreeNodos[] EndGetTree(System.IAsyncResult result) {
                object[] _args = new object[0];
                AttrForm.DBService1.TreeNodos[] _result = ((AttrForm.DBService1.TreeNodos[])(base.EndInvoke("GetTree", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetItem(int pIdNodo, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = pIdNodo;
                System.IAsyncResult _result = base.BeginInvoke("GetItem", _args, callback, asyncState);
                return _result;
            }
            
            public AttrForm.DBService1.TreeEstructuraItems[] EndGetItem(System.IAsyncResult result) {
                object[] _args = new object[0];
                AttrForm.DBService1.TreeEstructuraItems[] _result = ((AttrForm.DBService1.TreeEstructuraItems[])(base.EndInvoke("GetItem", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginSaveNodeEstructure(int pIDTree, bool pEsReq, bool pSolol, bool pMulti, string pSubTipo, string pOrigDatos, string pValores, string pRuta, string pMetodo, string pTipo, int pLargo, int pDec, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[12];
                _args[0] = pIDTree;
                _args[1] = pEsReq;
                _args[2] = pSolol;
                _args[3] = pMulti;
                _args[4] = pSubTipo;
                _args[5] = pOrigDatos;
                _args[6] = pValores;
                _args[7] = pRuta;
                _args[8] = pMetodo;
                _args[9] = pTipo;
                _args[10] = pLargo;
                _args[11] = pDec;
                System.IAsyncResult _result = base.BeginInvoke("SaveNodeEstructure", _args, callback, asyncState);
                return _result;
            }
            
            public void EndSaveNodeEstructure(System.IAsyncResult result) {
                object[] _args = new object[0];
                base.EndInvoke("SaveNodeEstructure", _args, result);
            }
        }
    }
}
