#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión del motor en tiempo de ejecución:2.0.50727.3603
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[System.Data.Linq.Mapping.DatabaseAttribute(Name="formFlows")]
public partial class DataClassesDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  partial void InsertAtributoInformacionGeneral(AtributoInformacionGeneral instance);
  partial void UpdateAtributoInformacionGeneral(AtributoInformacionGeneral instance);
  partial void DeleteAtributoInformacionGeneral(AtributoInformacionGeneral instance);
  #endregion
	
	public DataClassesDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["formFlowsConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<AtributoInformacionGeneral> AtributoInformacionGeneral
	{
		get
		{
			return this.GetTable<AtributoInformacionGeneral>();
		}
	}
	
	public System.Data.Linq.Table<FamiliaAtributo> FamiliaAtributo
	{
		get
		{
			return this.GetTable<FamiliaAtributo>();
		}
	}
}

[Table(Name="dbo.AtributoInformacionGeneral")]
public partial class AtributoInformacionGeneral : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _Id;
	
	private System.Nullable<int> _Identificador;
	
	private string _Autor;
	
	private System.Nullable<int> _Version;
	
	private System.Nullable<System.DateTime> _FechaCreacion;
	
	private System.Nullable<System.DateTime> _FechaVigenciaDesde;
	
	private System.Nullable<System.DateTime> _FechaVigenciaHasta;
	
	private string _Nombre;
	
	private string _Descripcion;
	
	private System.Nullable<byte> _EsModificable;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnIdentificadorChanging(System.Nullable<int> value);
    partial void OnIdentificadorChanged();
    partial void OnAutorChanging(string value);
    partial void OnAutorChanged();
    partial void OnVersionChanging(System.Nullable<int> value);
    partial void OnVersionChanged();
    partial void OnFechaCreacionChanging(System.Nullable<System.DateTime> value);
    partial void OnFechaCreacionChanged();
    partial void OnFechaVigenciaDesdeChanging(System.Nullable<System.DateTime> value);
    partial void OnFechaVigenciaDesdeChanged();
    partial void OnFechaVigenciaHastaChanging(System.Nullable<System.DateTime> value);
    partial void OnFechaVigenciaHastaChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnDescripcionChanging(string value);
    partial void OnDescripcionChanged();
    partial void OnEsModificableChanging(System.Nullable<byte> value);
    partial void OnEsModificableChanged();
    #endregion
	
	public AtributoInformacionGeneral()
	{
		OnCreated();
	}
	
	[Column(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int Id
	{
		get
		{
			return this._Id;
		}
		set
		{
			if ((this._Id != value))
			{
				this.OnIdChanging(value);
				this.SendPropertyChanging();
				this._Id = value;
				this.SendPropertyChanged("Id");
				this.OnIdChanged();
			}
		}
	}
	
	[Column(Storage="_Identificador", DbType="Int")]
	public System.Nullable<int> Identificador
	{
		get
		{
			return this._Identificador;
		}
		set
		{
			if ((this._Identificador != value))
			{
				this.OnIdentificadorChanging(value);
				this.SendPropertyChanging();
				this._Identificador = value;
				this.SendPropertyChanged("Identificador");
				this.OnIdentificadorChanged();
			}
		}
	}
	
	[Column(Storage="_Autor", DbType="VarChar(255)")]
	public string Autor
	{
		get
		{
			return this._Autor;
		}
		set
		{
			if ((this._Autor != value))
			{
				this.OnAutorChanging(value);
				this.SendPropertyChanging();
				this._Autor = value;
				this.SendPropertyChanged("Autor");
				this.OnAutorChanged();
			}
		}
	}
	
	[Column(Storage="_Version", DbType="Int")]
	public System.Nullable<int> Version
	{
		get
		{
			return this._Version;
		}
		set
		{
			if ((this._Version != value))
			{
				this.OnVersionChanging(value);
				this.SendPropertyChanging();
				this._Version = value;
				this.SendPropertyChanged("Version");
				this.OnVersionChanged();
			}
		}
	}
	
	[Column(Storage="_FechaCreacion", DbType="DateTime")]
	public System.Nullable<System.DateTime> FechaCreacion
	{
		get
		{
			return this._FechaCreacion;
		}
		set
		{
			if ((this._FechaCreacion != value))
			{
				this.OnFechaCreacionChanging(value);
				this.SendPropertyChanging();
				this._FechaCreacion = value;
				this.SendPropertyChanged("FechaCreacion");
				this.OnFechaCreacionChanged();
			}
		}
	}
	
	[Column(Storage="_FechaVigenciaDesde", DbType="DateTime")]
	public System.Nullable<System.DateTime> FechaVigenciaDesde
	{
		get
		{
			return this._FechaVigenciaDesde;
		}
		set
		{
			if ((this._FechaVigenciaDesde != value))
			{
				this.OnFechaVigenciaDesdeChanging(value);
				this.SendPropertyChanging();
				this._FechaVigenciaDesde = value;
				this.SendPropertyChanged("FechaVigenciaDesde");
				this.OnFechaVigenciaDesdeChanged();
			}
		}
	}
	
	[Column(Storage="_FechaVigenciaHasta", DbType="DateTime")]
	public System.Nullable<System.DateTime> FechaVigenciaHasta
	{
		get
		{
			return this._FechaVigenciaHasta;
		}
		set
		{
			if ((this._FechaVigenciaHasta != value))
			{
				this.OnFechaVigenciaHastaChanging(value);
				this.SendPropertyChanging();
				this._FechaVigenciaHasta = value;
				this.SendPropertyChanged("FechaVigenciaHasta");
				this.OnFechaVigenciaHastaChanged();
			}
		}
	}
	
	[Column(Storage="_Nombre", DbType="VarChar(100)")]
	public string Nombre
	{
		get
		{
			return this._Nombre;
		}
		set
		{
			if ((this._Nombre != value))
			{
				this.OnNombreChanging(value);
				this.SendPropertyChanging();
				this._Nombre = value;
				this.SendPropertyChanged("Nombre");
				this.OnNombreChanged();
			}
		}
	}
	
	[Column(Storage="_Descripcion", DbType="VarChar(MAX)")]
	public string Descripcion
	{
		get
		{
			return this._Descripcion;
		}
		set
		{
			if ((this._Descripcion != value))
			{
				this.OnDescripcionChanging(value);
				this.SendPropertyChanging();
				this._Descripcion = value;
				this.SendPropertyChanged("Descripcion");
				this.OnDescripcionChanged();
			}
		}
	}
	
	[Column(Storage="_EsModificable", DbType="TinyInt")]
	public System.Nullable<byte> EsModificable
	{
		get
		{
			return this._EsModificable;
		}
		set
		{
			if ((this._EsModificable != value))
			{
				this.OnEsModificableChanging(value);
				this.SendPropertyChanging();
				this._EsModificable = value;
				this.SendPropertyChanged("EsModificable");
				this.OnEsModificableChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[Table(Name="dbo.FamiliaAtributo")]
public partial class FamiliaAtributo
{
	
	private System.Nullable<int> _idFamilia;
	
	private System.Nullable<int> _idAtributo;
	
	public FamiliaAtributo()
	{
	}
	
	[Column(Storage="_idFamilia", DbType="Int")]
	public System.Nullable<int> idFamilia
	{
		get
		{
			return this._idFamilia;
		}
		set
		{
			if ((this._idFamilia != value))
			{
				this._idFamilia = value;
			}
		}
	}
	
	[Column(Storage="_idAtributo", DbType="Int")]
	public System.Nullable<int> idAtributo
	{
		get
		{
			return this._idAtributo;
		}
		set
		{
			if ((this._idAtributo != value))
			{
				this._idAtributo = value;
			}
		}
	}
}
#pragma warning restore 1591
